City-of-Helsinki/linkedevents

events/api.py
events/importer/matko.py

Fix error which occurs when an event has a Keyword having slash '/' in the name, e.g. "pop/rock". 
Example event:
http://api.hel.fi/linkedevents/v0.1/event/matko%3A1487528138/

Fix matko pop/rock Keyword id issue

---

events/management/commands/add_helsinki_audience.py

The command creates new SOTE keywords and a new keyword set for
Helsinki audience keywords. Helsinki audience keyword set contains
the newly created SOTE keywords, some old YSO SOTE keywords and YSO
keywords that correspond to old hel.fi audience keywords.
The command also adds audience YSO keywords to events that have matching
hel.fi audience keywords.
Closes #118

Add YSO audience management script

---

events/api.py
events/tests/test_event_post.py

* Require `description` and `short_description` in languages matching `name`
* Require price info for published events

Validation fixes

---

events/importer/yso.py
events/management/commands/update_all_n_events.py
events/models.py
events/sql.py

Instead of using the Django ORM, let's use SQL to figure out how many events each keyword has! ✨ 
Given a test database with 4431 events and 28054 keywords, `update_all_n_events` now finishes in about 5 seconds; with the code at `master`, it would have taken, extrapolating from the original 2.5 seconds per `recache_n_events`, about 70 000 seconds, so that's, uh, a 14 000× speed-up.
Single calls to `recache_n_events` become faster too, but not quite as dramatically (only a 1.94× speedup:)
```
(linkedevents) ~/b/linkedevents (n-event-up) $ time python update_50_times.py
3.12 real         0.82 user         0.09 sys
(linkedevents) ~/b/linkedevents (master) $ time python update_50_times.py
6.06 real         0.96 user         0.08 sys
```

Use SQL for caching n_events

---

events/api.py
events/models.py

* Speed up recache_n_events_in_location: Use the queryset update API to skip the position/divisions save when we certifiably won't need it.
* If the description doesn't contain any tag-like things (<>&), no need to try and parse it as HTML, right?
* Audience and in_language were missing prefetches, causing extraneous queries for them

Tiny optimizations

---

events/api.py

Resolves https://github.com/City-of-Helsinki/linkedevents/issues/204
Allow to filter by multiple comma-separated `publisher` parameters, in the same way as `data_source`.
Note: untested, but CI passes.

Allow to filter by multiple publishers

---

events/api.py

It would be useful to use multiple `data_source` values with the `keyword` API.
For example:
https://api.hel.fi/linkedevents/v1/keyword/?data_source=helmet 119 results
https://api.hel.fi/linkedevents/v1/keyword/?data_source=yso 326 results
But right now:
https://api.hel.fi/linkedevents/v1/keyword/?data_source=helmet,yso 0 results
Untested, but the CI passes.
Do the docs need updating for this somewhere? Same question for yesterday's https://github.com/City-of-Helsinki/linkedevents/pull/205.

Allow multiple data_source for keyword API

---

events/__init__.py
events/api.py
events/apps.py
events/signals.py
events/tests/test_api.py
events/tests/test_signals.py
helevents/models.py
helevents/tests/test_models.py
requirements.in
requirements.txt

When filtering the objects with publishers, the REST API will also return objects that are published by a replaced organization when a replacing organization is provided. Also it will return objects for replacing organization if a replaced organization is provided.

 Allow fetching objects published by replaced/replacing organization

---

events/api.py
events/tests/test_api.py
events/tests/test_event_auth_api.py
helevents/models.py
helevents/tests/test_models.py
requirements.in
requirements.txt

The `responsible_organization` field is removed from Organization model, and the affiliated organizations are part of the organization hierarchical tree. We need to change the REST API and permission check accordingly.
Refs: https://github.com/City-of-Helsinki/linkedevents/issues/248

Corresponding changes in Organization REST API and permission check for Organization model

---

events/api.py
events/tests/test_event_get.py

Added query parameters to filter events according to their publication_status draft events can still only be seen from users organization

Added publication status filter

---

events/importer/base.py
events/importer/espoo.py
events/importer/harrastushaku.py
events/importer/helmet.py
events/importer/kulke.py
events/importer/lippupiste.py
events/importer/matko.py
events/importer/sync.py
events/importer/tprek.py
events/importer/util.py
events/importer/yso.py
events/management/commands/event_import.py
linkedevents/settings.py

All importers are changed to use logging.* functions for
logging instead of prints. Also removed the superfluous
logger created in base.py. Django has already created a
logger for us, therefore we can just use `logging`.
Default log format has been changed to include severity
and module name.
the little-used verbosity flag usage has been removed
from importers. Instead messages are tagged with log
level. If verbosity flag is desired, it can be used to
control logging level.

Cleanup importer logging

---

linkedevents/settings.py
requirements.in
requirements.txt

Old "raven" SDK does not work for some unfathomable raisin. Let's just upgrade the SDK and furgeddeaboutit.

Switch to current Sentry Python SDK

---

events/importer/kulke.py

About:
> This regexp does not probably do what you would like it to do.
> 
> ```
> >>> my_re = re.compile(r'^\D*(\d{1,2}).(\d{1,2}).[v.|år].+$')
> >>> my_re.match('Yes 45678-åå').groups()
> ('45', '78')
> >>> my_re.match('"Introduction 101"|by me').groups()
> ('1', '1')
> ```
> 
> The regular expression you're aiming at is probably:
> `^\D*(\d\d?)-(\d\d?)[- ](v|år).*$`
The things that are different between the regexes:
* To capture a two-digit number, like “something something 11 something something” for 11, I’m using `\d{1,2}` and you’re using` \d\d?` . I think both of them achieve the same goal and I can use both of them. I think first version is just a tad more readable because I read it as `a digit, occurring 1 or 2 times` and I read second version like `a digit. and then a digit, …

TH-161 Kulke course name regex parsing improvements

---

docker/django/Dockerfile

This fixes the error thrown saying:
CommandError: Can't find msguniq. Make sure you have GNU gettext tools 0.15 or newer installed

add gettext to Django's Dockerfile

---

notifications/models.py
notifications/tests/test_notifications.py

Converts the datetime object to the current timezone before rendering.
`format_datetime_tz` was also removed, because it would not work as expected after this change.

Notification timezone fix

---

events/models.py
events/tests/test_notifications.py

* Stop sending "Event published" and "Event deleted" notifications to the last modifier of the event
* Send "Event deleted" notifications only from draft events

Notification fixes

---

events/api.py
events/tests/test_event_get.py

Currently, the event API text search filters events only based on Event fields. Thus, searching with a place name doesn't bring any results unless the place name is included, e.g., in the location_extra_info
field of an event.
To be able to search with place names, this change supplements the text search filters with the following place fields: name, description, info_url, street_address, address_locality, telephone.
As a result, the text query in the API searches for the given string both in event and place fields thus broadening the search.

Filter events also based on place fields

---

events/signals.py
linkedevents/settings.py

When using Docker in local dev env, an admin user is created so that we can immediately login to django admin views after the server is run.
At the moment, `docker-compose up` crashes on the first run because it tries to send an email when the admin user is created. This PR fixes this, by checking if DEBUG is False to send the email after a user is created.

Update EMAIL_BACKEND in local dev env

---

docker-compose.yml

/var/lib/postgresql/data is the correct path for docker volume to mange based on [postgres on docker hub](https://hub.docker.com/_/postgres/) at "Where to Store Data"

Fix docker-compose volume path for postgres

---

events/api.py
events/tests/test_event_get.py
helevents/templates/rest_framework/event_list.html

The PR adds `audience_min_age_lt`, `audience_min_age_gt`, `audience_max_age_lt`, `audience_max_age_gt` filtering together with the required tests and documentation. It keeps the existing `audience_max_age` and `audience_min_age` filters for compatibility purposes, but marks them obsolete in the documentation.

HAP-94 add audience min_age and max_age filters

---

events/api.py
events/tests/test_event_get.py
helevents/templates/rest_framework/event_list.html
requirements-dev.in
requirements-dev.txt

This PR adds start and end time filtering for the events, so that it becomes possible to filter for the events that, for example, start before 16 or end after 17:30
The added parameters are `starts_after`, `starts_before`,`ends_after`, and `ends_before`.
Sample usage:
https://api.hel.fi/linkedevents/v1/event/?starts_after=16:40

TH-609 start/end time filter

---

events/api.py
events/tests/test_event_get.py

This PR adds the combined search for event content and keywords. The same keyword is searched for in the event and is used to retrieve the keywords which are then added to the event search. As this is just the first iteration, no documentation is added so far.

combine text and keyword searches

---

events/api.py
events/tests/test_event_get.py

-comma separated search terms in `event/?combined_text` are now ANDed. i.e. `event/?combined_text=lapset,aikuiset` searches for the event that would contain both lapset and aikuiset in their translated fields or keywords.

make search terms ANDable

---

events/api.py
events/tests/conftest.py
events/tests/test_event_get.py

When event_type query parameter is not specified only events of type "General" are returned.

LINK-490 Set "General" as default type for event list

---

events/api.py
events/models.py

Querying *.objects.all() for related fields results in huge requests whenever an Event is updated. Internal DRF mechanics for related fields as specified in relations.py uses get() for every updated related field and presumes an existing queryset. The goal of this bug fix is to provide querysets for the related fields that would contain only the related objects mentioned in the request

LINK-485. Fix failing PUT requests

---

events/api.py
events/tests/conftest.py
events/tests/test_event_put.py

During update the events are passed through `EventViewset.filter_queryset()` for authorization check up, this method invokes  `_filter_queryset`. The latter is used to filter events by params in GET request and should not be used for other request methods.

LINK-533 Fix bulk event update for non general event type

---

README.md
docker/postgres/Dockerfile
docker/postgres/docker-entrypoint.sh
linkedevents/settings.py

This PR makes some changes to dev env setup.
- [Fix issue where base image initialization script has been renamed](https://github.com/City-of-Helsinki/docker-images/pull/18).
- Add `hstore` and `pg_trgm` extensions to docker postgres default DB template (`template1`). **Note** Initialization script is only run for a fresh DB container, so existing DBs need to run this manually or recreate the DB container and data.
- Add note about Postgres pg_trgm extension to README.md
For silencing a warning
- Add [`DEFAULT_AUTO_FIELD`](https://docs.djangoproject.com/en/3.2/ref/settings/#std-setting-DEFAULT_AUTO_FIELD) setting with the current default value.

Improve docker postgis initialization

---

README.md
requirements.in
requirements.txt

django-haystack==3.2.1 supports ES 1, 2, 5 ja 7 versions. Currently the unconstrainted elasticsearch dependency picks v8 package.
Without restricting to v7, `python manage.py event_import tprek --places` breaks with `TypeError: bulk() got an unexpected keyword argument 'doc_type'`

Fix elasticsearch dep

---

events/importer/helmet.py

self.system_data_source was set to a tuple and if a new place was created 
with defaults the foreign key relation would be set to the tuple instead of 
data source instance leading to an error.

Fix issue in helmet import

---

linkedevents/settings.py

Remove deprecated use of `imp` module as described @ https://stackoverflow.com/questions/32175693/python-importlibs-analogue-for-imp-new-module
`imp` was deprecated in 3.4 and will be removed in 3.12 ( https://docs.python.org/3/library/imp.html )

Fix deprecated use of imp

---

requirements.in
requirements.txt

`django-haystack` has an optional extra requirement, which currently will limit `elasticsearch` package to `elasticsearch>=5,<8`

Make django-haystack manage elasticsearch package version

---

docker-compose.yml

`unless-stopped` is similar to `always` flag, but it doesn't restart any stopped containers when the Docker daemon restarts (e.g. on boot).
https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy

Prevent stopped docker-compose containers restarting on boot

---

events/api.py
events/tests/test_event_get.py
helevents/templates/rest_framework/event_list.html

Adds two new event filters, `dwithin_origin` and `dwithin_metres`, which filters all events within the given distance (in metres) from the origin point (x, y).
E.g.
`/v1/event/?dwithin_origin=24.941430575828296,60.17186028180228&dwithin_metres=1000`
Get all events within 1 km radius of Helsinki Central Station.
Refs LINK-952

LINK-952: Add distance filter (aka "circle filter")

---

.github/workflows/ci.yml
sonar-project.properties

SonarCloud was giving warnings after scanning, so two changes were needed:
* changed the GHA job to not use a shallow clone ([more info](https://community.sonarsource.com/t/sonarcloud-with-github-actions/22713/2))
* added a workaround that overrides source path in the generated coverage report file ([more info](https://community.sonarsource.com/t/sonar-on-github-actions-with-python-coverage-source-issue/36057))
Also excluded tests from Sonar scans.

Fix SonarCloud warnings

---

events/api.py
events/importer/base.py
events/renderers/docx.py
events/tests/test_utils.py
events/utils.py

Warning: Don't hurt yourself trying to read this.
Backstory: So.. in the Events API, the fields `start_time`, `end_time` and `date_published` are DateTimeFields, but utilizing a surprise `to_internal_value` method  some preprocessing is done to allow them also be date strings or special nouns like `now` or `today`. Additionally for dates (and `today`)  there's a concept of `is_start`, which if `False`, means the date is actually not the given date but the next day at 00:00:00. Because there are two different virtual types living the same field, there's a concept of `is_exact`. If the object is not exact, it means it's a date (disguised as a datetime). This information is stored in a helper field `has_start_time` which is `False` if the object is not `is_exact`.  This allows us to use a …

Fix overflow and DST handling in parse_time and add tests

---

.github/workflows/ci.yml
docker/django/.env.example
linkedevents/settings.py
linkedevents/test_settings.py

Secret key from a generated file was used by default, which means it changes every time a new container is started. The `SECRET_KEY` environment variable was not actually read into the `SECRET_KEY` setting.

LINK-1158 | Get SECRET_KEY from the environment variable by default

---

docker/django/Dockerfile

Platta needs more permissive permissions for the template directory.
Refs LINK-1138, LINK-1081

Fix template dir permission for production

---

config_dev.toml.example

config_dev.toml.example still has some old mailgun environment variable. Use same variable names as in linkedevents/settings.py

Unify mailgun environment variable naming

---

events/api.py
events/tests/conftest.py
events/tests/test_api.py
events/tests/test_event_images_v1.py
helcourses/templates/rest_framework/api.html
helevents/templates/rest_framework/api.html
helevents/templates/rest_framework/image_list.html

e.g. https://linkedcomponents-ui-dev.agw.arodevtest.hel.fi/fi/administration/images?text=musiikki calls https://linkedevents-api-dev.agw.arodevtest.hel.fi/v1/image/?page=1&page_size=10&sort=-last_modified_time&text=musiikki&nocache=true to get images filtered by name or image alt text. However the text filtering is not implemented to API so far. Also sorting by id and name are missing.
Purpose of this PR is to implemented those missing features.
PR content:
- Support filtering images by text included in name or alt text
- Allow to sorter images by id and name
- Add documentation for image list endpoint
[LINK-348](https://helsinkisolutionoffice.atlassian.net/browse/LINK-348)
[LINK-348]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …

LINK-348 | Support filtering images by text

---

docker/django/.env.example
docker/django/Dockerfile

This PR makes the local dev env to use the media volume created in `docker-compose.yml`
- Set MEDIA_ROOT for .env.example 
- Set permission for development env MEDIA_ROOT mount

LINK-1233 | Make local Docker env to use media volume

---

events/custom_elasticsearch_search_backend.py

Now that platta is running ES7 switch to using elasticsearch7_backend in django-haystack as pointed out by @charn

Update CustomEsSearchBackend to use elasticsearch7_backend

---

events/api.py
events/tests/test_event_get.py
helevents/templates/rest_framework/event_list.html

Modify registration parameter to return events with a registration when true, and without a registration when false
[LINK-1250](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1250)
[LINK-1250]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1250 | Events without registration

---

registrations/api.py
registrations/tests/test_registration_admin_side.py

Don't filter registrations by event_type by default. It causes 404 errors when requesting a single registration which has event_type course or volunteering
[LINK-1027](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1027)
**Producing the bug before the fix:**
1. Create an a new event
2. Create a registrations and use created event in it
3. Change event type of the event to course or volunteering
http://localhost:8080/v1/registration/[id]/ returns 404 error
e.g. https://linkedevents-api-dev.agw.arodevtest.hel.fi/v1/registration/28/?include=signups&nocache=true
[LINK-1027]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1027 | Fix "some registrations not found" bug

---

events/api.py
events/models.py
events/tests/test_event_images_v1.py
events/tests/test_image_delete.py
events/tests/test_models.py

Allow all admin users to delete the image, not only if it's user's default organization
Move image delete related tests to separate file
[LINK-1057](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1057)
[LINK-1057]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1057 | Allow all admin users of the image organization to delete image

---

.github/workflows/ci.yml

> On April 12, 2023, Codecov removed the codecov package from PyPI. Our intent was to remove a deprecated, rarely-used package from active support.
https://about.codecov.io/blog/message-regarding-the-pypi-package/
This PR fixes the broken CI caused by this.

Remove deprecated codecov dependency from CI

---

events/api.py

Motivation for this PR is to be able to use e.g. location ids with %xx escapes when creating a new event. See https://helsinkisolutionoffice.atlassian.net/browse/LINK-1096 to see details of the bug
Replace %xx escapes with their single-character equivalent when parsing object ids
[LINK-763](https://helsinkisolutionoffice.atlassian.net/browse/LINK-763)
[LINK-1096](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1096)
[LINK-763]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LINK-1096]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-763, LINK-1096 | Replace %xx escapes with their single-character equivalent in id

---

events/admin.py

Show language specific name fields in Django Admin when editing a language
[LINK-373](https://helsinkisolutionoffice.atlassian.net/browse/LINK-373)
[LINK-373]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-373 |. Language name translations

---

registrations/admin.py
registrations/tests/factories.py
registrations/tests/test_admin.py

Add registration model to Django admin
[LINK-1289](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1289)
This PR and https://github.com/City-of-Helsinki/linkedevents/pull/575 will replace https://github.com/City-of-Helsinki/linkedevents/pull/565 which contains several separate features
[LINK-1289]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1289 | Add registration model to Django admin

---

requirements-dev.txt
requirements.in
requirements.txt

Latest django-orghierarchy can import organizations from Open Ahjo API.
Example for using this importer:
```bash
python manage.py import_organizations https://dev.hel.fi/paatokset/v1/organization/?limit=1000 -c openahjo -s OpenAhjoAPI:ahjo
```

LINK-1147 | Bump django-orghierachy to get Open Ahjo importer

---

requirements.txt

Adds data_source list filters to Django admin organization related views.

LINK-1147 | Bump django-orghierarchy to 0.3.0

---

events/api.py
helcourses/templates/rest_framework/api.html
helevents/templates/rest_framework/api.html
helevents/templates/rest_framework/registration_list.html
registrations/api.py
registrations/models.py
registrations/serializers.py
registrations/tests/test_models.py
registrations/tests/test_registration_admin_side.py
registrations/tests/test_registration_get.py
registrations/tests/test_registration_post.py
registrations/tests/test_registration_put.py

At the moment UI has to first load registration data and after that event information in separate request. Motivation for this PR is to allow to request event data via registration endpoints
[LINK-664](https://helsinkisolutionoffice.atlassian.net/browse/LINK-664)
e.g. http://localhost:8080/v1/registration/?include=event,location,keywords,in_language,audience
[LINK-664]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Link to UI PRs: https://github.com/City-of-Helsinki/linkedcomponents-ui/pull/175 and https://github.com/City-of-Helsinki/linkedregistrations-ui/pull/48

LINK-664 | Support include parameter in registration endpoints

---

docker-compose.yml

`docker compose build` command returns  `no match for platform in manifest` error. The problem occurs at least with macOS 13.2.1 
Use `linux/amd64` as platform for postgres and django services in docker-compose.yml to fix the problem
[LINK-1306](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1306)
[LINK-1306]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1306 | Define platform for postgres and django services in docker-compose.yml

---

docker-compose.yml
registrations/api.py
registrations/serializers.py
registrations/templates/message_to_signup.html
registrations/tests/conftest.py
registrations/tests/test_send_message.py
registrations/utils.py

- Endpoint to send an email message to all or selected signups.
- Email uses Linked Registration email template for styling
- Email subject and body are required fields.
- User can send email to all signups of the registration by leaving signups attribute empty or send the email to selected signups
[LINK-1271](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1271)
POST http://linkedevents-backend:8080/v1/registration/2/send_message/
```
{
"body":"<p>Message1</p><p>Message2</p>",
"subject": "MESSAGE SUBJECT",
"signups": [2]
}
```
PR for FE: https://github.com/City-of-Helsinki/linkedcomponents-ui/pull/180
[LINK-1271]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1271 | Endpoint to send message to all or selected registration signups

---

events/api.py
events/tests/test_event_get.py

queryset.filter was never called when handling keyword_set_OR filter. Added queryset.filter to the end of that parameter handling.
[LINK-1320](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1320)
[LINK-1320]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1320 | Fix event keyword_set_OR filter

---

events/api.py
events/tests/test_event_get.py
helevents/templates/rest_framework/event_list.html

Allows passing multiple parameters to `event_status` -field separated by a comma. Returns events that match any of the given statuses. i.e. `?event_status=EventCancelled,EventRescheduled`
[LINK-1172](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1172)
[LINK-1172]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1172 | Allow searching multiple event statuses in API

---

helevents/service_tasks/daily_tasks.sh
helevents/service_tasks/hourly_tasks.sh

Added bash scripts for running hourly and daily periodic service tasks which include importers and cache-related stuff. The main purpose for these is to be run in the new Helsinki production environment. The implementations are pretty much copied straight from the old production Helsinki environment, the only changes being file-logging and healthcheck.io usage removal.

LINK-1080 | Add Helsinki service task scripts

---

events/api.py
events/auth.py
events/models.py
events/permissions.py
events/tests/conftest.py
events/tests/factories.py
events/tests/test_api.py
events/tests/test_auth.py
events/tests/test_event_auth_api.py
events/tests/test_event_put.py
events/tests/test_external_user.py
events/tests/test_permissions.py
events/tests/utils.py
events/utils.py
helevents/models.py
helevents/tests/test_models.py
linkedevents/settings.py
linkedevents/tests/conftest.py
registrations/api.py
registrations/models.py
registrations/serializers.py
registrations/tests/factories.py

This PR allows event creation, modifying and deletion for external users, i.e. users that do not belong to an organization. This means that this also adds support for non-organization users. There's also a lot of refactoring involved.
Related issue: [LINK-1164](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1164)
(in no order of importance)
- New users are no longer automatically assigned to a default organization
- `publisher` field in event payload is no longer required
- If missing or null, it gets automatically replaced
- If creating, it uses the default organization
- If updating, it uses the target event's organization
- Remove the organization logic from `DataSourceResourceEditPermission`
- New permissions:
- `IsReadOnly`, check if HTTP method is in safe methods aka …

LINK-1164: Allow event creation, modifying and deleting for external users

---

events/importer/kulke.py
linkedevents/settings.py

Instead of reading event/category data from XML files exported from Elis using a script, directly call Elis API in the KulKe importer.
Also fix logging warnings for differing groups.

LIIKUNTA-450 | Fetch data directly from Elis in kulke importer

---

events/importer/yso.py

Deprecate and replace functionality failed if an invalid YSO id was encountered.

LINK-1299 | YSO importer keyword deprecation handles invalid YSO ids

---

events/admin.py
events/api.py
events/tests/conftest.py
registrations/admin.py
registrations/models.py
registrations/serializers.py
registrations/tests/test_admin.py
registrations/tests/test_registration_admin_side.py
registrations/tests/test_registration_get.py
registrations/tests/test_seatsreservation_post.py
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_post.py

Fix some pytest warnings in registration tests
- Replace deprecated ugettext with gettext
- Replace deprecated assertEquals with assertEqual
- Use localtime instead of datetime.now
Prevent to reserve seats or signup if enrolment is not open
PR for frontend implementation: https://github.com/City-of-Helsinki/linkedcomponents-ui/pull/188
[LINK-1362](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1362)
[LINK-1362]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1362 | Prevent to signup to event if enrolment is not open

---

events/api.py
events/tests/test_organization_api.py

At the moment `admin_users` and `regular_users` of an organization are not saved when creating a new organization. Fix this by using OrganizationDetailSerializer also when updating an organization instead of having separate serializer for update and having all logic to create/update organization in a single serializer. 
Change format of users in payload from
```
"admin_users": {
"username": [
"u-ui745qfmxmi63dvsbjmavaacea"
]
},
```
to
```
"admin_users": ["u-ui745qfmxmi63dvsbjmavaacea"],
```
Show `admin_users` and `regular_users` field only for admin users and hide them if user has insufficient permissions.
PR for UI implementation: https://github.com/City-of-Helsinki/linkedcomponents-ui/pull/189
[LINK-1322](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1322)
[LINK-1322]: …

LINK-1322 | Save admin and regular users when creating an organization

---

events/api.py
events/importer/base.py
events/importer/yso.py
events/models.py
events/tests/factories.py
events/tests/test_keyword.py

Kulke importer was running into some issues when trying to save an event (course) with deprecated keywords. This PR adds logic which will replace or just delete deprecated keywords from an event upon import. Also added fixes for the YSO keyword importer and the keyword replacement logic.
**Manual testing results**
I deprecated some keywords manually for event `kulke:59821`. Deprecated keyword without a replacement was removed and keyword with a replacement was replaced. Works-on-my-machine :rainbow:  :tm:
```
2023-06-23 00:11:28,994 events.importer.base DEBUG: Checking for deprecated keywords in attribute 'keywords' for event Manual Productions: kesäkurssi – 9-12 v klo 9-14.30 (kulke:59821) 2023-06-12 06:00:00+00:00
2023-06-23 00:11:29,018 events.importer.base WARNING: Replacing …
```

LINK-1347 | Fix deprecated keywords upon import

---

events/models.py
locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
registrations/api.py
registrations/models.py
registrations/serializers.py
registrations/templates/cancellation_confirmation.html
registrations/templates/signup_confirmation_to_waiting_list.html
registrations/templates/signup_transferred_as_participant.html
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_post.py

- Send email to participant if he is added to waiting list or moved from waiting list as participant
- Translate some event texts to Finnish and Swedish
- Translating event type id texts breaks event creations so make them not-translatable
[LINK-1370](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1370)
[LINK-1370]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1370 | Send email to participant when she's moved from waiting list to participant

---

.prod/uwsgi_configuration.ini

Reload workers regularly to keep memory fresh and ease potential memory leaks.

LINK-1392 | Free used memory from uWSGI processes

---

.prod/uwsgi_configuration.ini
docker/django/docker-entrypoint.sh

This PR adds configuration options for controlling the amount of uWSGI processes, defaulting to the current amount.

LINK-1393 | Control uWSGI process amount

---

docker/django/.env.example
docker/django/Dockerfile
docker/django/docker-entrypoint.sh

This change builds the translations for the production container in `Dockerfile`. Translations were previously only built for the local development container, which has some issues since the `docker-compose.yml` mounts over the ` /app` folder gets. For compiling translations in development container a `COMPILE_TRANSLATIONS` variable was added.

Fix: build translations for production container

---

events/importer/kulke.py
events/models.py
events/tests/factories.py
events/tests/importers/test_kulke.py
requirements-dev.in
requirements-dev.txt

If there are events that have previously been imported, but have since been removed in Elis, there's currently no mechanism to remove them from LE. This PR adds such a mechanism. Basically we check for any events that we have previously imported that no longer exist in Elis. We won't touch events that are older than the start date we use for the Elis search though.
Also, the fix for the empty name issue in my previous PR was not sufficient, so I fixed that. The logic for taking the common part when creating a super event name should now work in all supported languages.
When reviewing, please pay special attention to the logic for selecting which events to delete.

Delete events not found in Elis in kulke importer

---

helevents/serializers.py
helevents/tests/test_user_get.py

This adds the is_external flag to the API.

LINK-1384 | Expose User.is_external property in the API

---

events/importer/harrastushaku.py
events/importer/kulke.py
events/importer/yso.py

- Add exception information in some of the kulke/harrastushaku importer error logs
- Also change the error messages for harrastushaku error loggers.
- These both are mostly for making Sentry more helpful.
- I also considered making `HarrastushakuException` related log messages into warnings, since they are essentially warnings, but wasn't quite sure how Sentry handles warnings, so left them as errors.
- Add YSO replacement for Suvilahti (deprecated: [Suvilahti](https://finto.fi/yso/fi/page/p27158), replaced by: [Suvilahti (Helsinki)](https://finto.fi/yso-paikat/fi/page/p508707))
- Due to this error: `Exception: Deprecating YSO keyword Suvilahti that is referenced in events <MultilingualBaseTreeQuerySet [<Event: D-A-D & Melrose (helsinki:af25a6ji4u) 2022-08-25 15:00:00+00:00>]>. No …

LINK-1080: Miscellaneous importer changes

---

events/auth.py
events/tests/test_auth.py
events/tests/test_permissions.py
helevents/models.py
linkedevents/settings.py

User.is_external checks the AMR claim value and and returns False if AD authentication is used.
AMR (Authentication Method Reference) should be a list of string that are identifiers for authentication methods used in the authentication. Tunnistamo however sets a simple string here, which is assumed in this implementation also.
Refs LINK-1394

LINK-1394 | User doing AD authentication is never considered to be an external user

---

azure-pipelines-build.yml
azure-pipelines-prod.yml
azure-pipelines-stage.yml

1) Trigger build on releasing a tag that starts with `release-`
2) set buildenv for release builds as PROD
3) Allow deploying only prod builds to production
4) Allow deploying all builds to staging
Ref [LINK-1407](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1407)
[LINK-1407]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Tweak azure pipelines for prod/staging builds and deployments

---

events/api.py
events/tests/test_event_get.py
events/tests/test_keyword.py

The use of distinct is extremely slow in the event listing. ~The need for distinct can be replaced in one-to-many and many-to-many relations by using
`exclude(~Q(relation=something)`. When excluding relations, Django automatically uses SQL EXISTS. Negating the Q statement will essentially create a NOT NOT EXISTS which the database then optimizes into plain EXISTS.~
DISTINCT can be avoided by utilizing EXISTS queries in filters that can create duplicate rows. Additionally some filter queries on m2m relations can be made still significantly faster if we target the through table directly to avoid unnecessary INNER JOIN by django.

Remove use of distinct in event listing

---

helevents/service_tasks/daily_tasks.sh
helevents/service_tasks/hourly_tasks.sh

Add kulke keywords import and harrastushaku places import in `hourly_tasks.sh` and `daily_tasks.sh`.
Some of the kulke/harrastushaku events (or at least Harrastushaku) require these. Causes `Keyword.DoesNotExist` in kulke & `Place.DoesNotExist` in HH otherwise. Tested with Harrastushaku importer locally; Kulke importer doesn't seem to work locally for me, but the error seems to have a similar root cause.
These weren't in the old production environment's crontab, so makes me wonder whether there's a good reason for it or not.

LINK-1080: Add missing imports (kulke keywords, harrastushaku places)

---

events/importer/harrastushaku.py

Full text search + trigram similarity can result in inappropriate keywords to be selected in events.
https://helsinkisolutionoffice.atlassian.net/browse/LINK-1420

Disable harrastushaku fuzzy keyword search

---

.prod/uwsgi_configuration.ini

Increasing the buffer-size will allow bigger requests which will allow e.g. to include big lists of AD-group memberships in a authentication token.
Refs LINK-1448

Increase the buffer-size for uWSGI

---

linkedevents/api.py
linkedevents/tests/test_api_root_view.py

Fixed API root view name which was erroneous "Custom Api Root" due to a regression introduced in 8ac8ec78c34aba7ee90159f64b7797a2a5dadd91.
Spotted by @charn 🦅 👁️

Fix api root view name

---

.prod/uwsgi_configuration.ini
docker/django/Dockerfile
docker/django/docker-entrypoint.sh

Support changing the URL prefix for Django by the way of the "mount" and "manage-script-name" directives in uwsgi
URL prefix is read from environment with default being "/".
Also includes a slight optimization for container shutdown speed

Support changing the URL prefix used by Django

---

events/permissions.py
events/tests/test_organization_api.py

Require user to be an admin to create a new organization. Ensure with tests also that update/destroy is allowed only for org admins. 
This does not give permissions to superusers. The OG implementation from last year did also not permit superusers.
Ref LINK-1386

Restrict creation/modification/delete of organizations

---

events/importer/kulke.py
events/tests/importers/test_kulke.py

This PR fixes a bug with kulke-importer removing events with other data sources as well.

LINK-1478 | Kulke importer removes only event with kulke data source

---

events/api.py
events/tests/test_event_get.py

Adds possibility to filter max- and min_attendee_capacity fields through gte, lte lookups. Such as `?max_attendee_capacity__gte=12`.
Also adds ordering capabilities for those fields
Refs LINK-1071

TILA-1071 | Add filters for event max- and min_attendee_capacity

---

locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
registrations/tests/test_signup_post.py

Current Finnish and Swedish translations of signup_confirmation.html template are incorrect.
They tell that the user is added to the waiting list, even though she already has a place in the event.
Fix translation in this PR.
[LINK-1471](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1471)
[LINK-1471]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1471 | Fix signup_confimation template translations

---

events/signals.py
registrations/tests/test_admin.py
registrations/tests/test_registration_post.py
registrations/tests/test_registration_put.py
registrations/tests/test_registration_user_access_invitation.py
registrations/tests/utils.py

If a superuser with an empty exists. `user_created_notification` will fail with `AnymailInvalidAddress`.

Fix user_created_notification failing on empty emails

---

events/api.py
events/permissions.py
events/tests/test_organization_api.py

DataSourceOrganizationEditPermission raised an error for anonymous users (no `admin_organizations` attribute in `AnonymousUser`). Changed it to check for authentication before doing anything else.
Also decoupled `DataSourceOrganizationEditPermission` from `DataSourceResourceEditPermission` to remove potential spaghetti code.
Refs [LINK-1495](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1495)
[LINK-1495]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1495: Fix organization edit permission

---

events/api.py

Division filtering ends up doing DISTINCT which ends up using on disk sort which kills the DB perf. Replace with EXISTS to avoid silly sorting

Make division filtering use exists instead of distinct

---

events/api.py
events/tests/test_event_get.py
helevents/templates/rest_framework/event_list.html

- Renames the newly introduced `max_attendee_capacity` and `min_attendee_capacity` filters to `maximum_attendee_capacity` and `minimum_attendee_capacity` to stay consistent with the model field names. 
- Adds documentation for the above filters
- Fix discovered typo in event_list.html 
Refs LINK-1071

LINK-1071 | Changes to attendee capacity filters

---

requirements.txt

Needed to bump social-auth-core (🤞 ) to get latest pyjwt. Previously used version of pyjwt had some security issues.
Refs RAT-18

Bump pyjwt, cryptography, social-auth-core

---

.prod/uwsgi_configuration.ini
docker/django/Dockerfile

This PR adds uwsgi-sentry plugin for uWSGI so that errors from uWSGI can be logged into sentry. This PR also adds `harakiri` to uWSGI configuration, which should take care of actually killing a long running uWSGI process.

LINK-1527 | Log uWSGI errors to sentry

---

.prod/uwsgi_configuration.ini

Lower the default harakiri time. If listen queue is not looking too bad, we can allow processing to continue with the `harakiri-graceful-queue-threshold`.
- harakiri-graceful-queue-threshold only triggers a harakiri if/when the listen queue crosses a threshold. Harakiri continues to be checked until the conditions are met.
- This configuration option was added in [uWSGI 2.0.22](https://github.com/unbit/uwsgi/compare/2.0.21...2.0.22)

LINK-1527 | uWSGI: Add harakiri-graceful-queue-thershold

---

helevents/models.py
helevents/serializers.py
helevents/tests/test_user_get.py
linkedevents/settings.py
registrations/api.py
registrations/permissions.py
registrations/serializers.py
registrations/tests/test_registration_get.py
registrations/tests/test_signup_get.py

After these changes, the "suomifi" identification will be required for registration users (`RegistrationUserAccess`) to access signup data.
[LINK-1449](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1449)
[LINK-1449]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1449 | Signups require strong identification from registration users

---

events/api.py
events/tests/test_keyword_get.py
events/tests/test_place_get.py

Fix duplicate queries for both place and keyword endpoints, move multiple select_related fields to prefetch_related because they are mostly null rows anyway, so joining is inefficient (especially with large page offsets), and add tests to keep an eye on the query numbers for default listings.
Ref https://helsinkisolutionoffice.atlassian.net/browse/LINK-1531

LINK-1531: Optimize place and keyword listings

---

events/__init__.py
notifications/__init__.py
registrations/__init__.py
registrations/api.py
registrations/apps.py
registrations/models.py
registrations/signals.py
registrations/tests/test_signup_group_delete.py
registrations/tests/test_signup_group_get.py

Makes it possible to delete a `SignUpGroup` instance together with related `SignUp` instances using just one API call.
[LINK-1075](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1075)
[LINK-1075]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1075, part 2 | Delete signup group

---

registrations/api.py
registrations/models.py
registrations/permissions.py
registrations/serializers.py
registrations/tests/test_models.py
registrations/tests/test_registration_get.py
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_get.py
registrations/tests/test_signup_group_delete.py
registrations/tests/test_signup_group_get.py
registrations/tests/test_signup_group_post.py
registrations/tests/test_signup_patch.py
registrations/tests/test_signup_post.py
registrations/tests/test_signup_put.py

Makes the following changes to registration permissions:
* Only a registration admin, a superuser or the "created user" is able to perform all CRUD operations on the endpoint `signup`.
* In addition to a regular admin, the registration admin will be able to perform all CRUD operations on the endpoint `registration`.
* A registration user (`RegistrationUserAccess`) is allowed to get a `registration`, but not allowed to do any other CRUD operations on that endpoint.
* A registration user (`RegistrationUserAccess`) is allowed to get or update a `signup`, but not allowed to do any other CRUD operations on that endpoint (updating will be limited to patching just `presence_status` in LINK-1429).
This PR is the second one of two PRs - the first PR (part 1) will bring the Django admin and …

LINK-1351, part 2 | Registration admin permissions

---

registrations/models.py

Ensures that some caught exceptions in the `registrations` app are logged into Sentry.
[LINK-1548](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1548)
[LINK-1548]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1548 | Log registrations exceptions to Sentry

---

events/models.py
events/tests/factories.py
events/tests/test_notifications.py

Draft events which are created using an API key shouldn't send any notifications for organization admin.

LINK-1498 | No draft notifications for events created with an API key

---

registrations/permissions.py
registrations/tests/test_registration_get.py

The `CanAccessRegistration.has_object_permission` wrongly used the `and` operator when checking permissions for the `GET` request, resulting in an admin user needing to be either a "registration user access" or "created_by" user in addition to being an admin. This has now been fixed by changing to the use of the `or` operator.
[LINK-1561](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1561)
[LINK-1561]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1561 | Fix registration GET permissions check

---

registrations/api.py
registrations/serializers.py
registrations/tests/test_send_message.py

Makes it possible to send messages to specific signup groups (to their responsible signups).
Also changes the individual signup messaging so that if any individual signups - that is, signups that don't belong to any group - are given to the endpoint, messages will be sent to them regardless of if they are responsible for a group or not (unless they were already processed through the group messaging).
[LINK-1490](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1490)
[LINK-1490]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1490 | Add possibility to send emails to specific registration signup groups

---

registrations/api.py
registrations/serializers.py
registrations/tests/test_signup_group_patch.py
registrations/tests/test_signup_group_put.py
registrations/tests/test_signup_post.py

Adds the possibility to update `SignUpGroup` instances and `SignUp` instances belonging to the groups. It is only allowed to edit the related `SignUp` instances' data - adding new sign-ups or deleting existing ones from groups needs to be done through the `signup` endpoint.
[LINK-1075](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1075)
[LINK-1075]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1075, part 3 | Update signup group

---

events/importer/harrastushaku.py
events/tests/importers/test_harrastushaku.py

Price is expected to be a translated field in the `Offer` model and in the LE API.
Partly reverts 96f51c5e68da0322f30deeeeff09dd0bbbecffa2

LINK-1500 | Fix missing prices for harrastushaku

---

registrations/api.py
registrations/tests/test_seatsreservation_post.py
registrations/tests/test_seatsreservation_put.py

Makes the `seat_reservation` endpoint require the user to be authenticated for all requests.
[LINK-1547](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1547)
[LINK-1547]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1547 | Require authentication in SeatReservationViewSet

---

registrations/serializers.py
registrations/tests/test_registration_get.py
registrations/tests/test_signup_get.py

To avoid showing all fields by default because of the use of `fields = "__all__"`, the fields have been explicitly defined for `SignUpSerializer` and `RegistrationBaseSerializer`. Tests have also been added for the serializers' fields.
[LINK-1550](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1550)
[LINK-1550]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1550 | Excplicitly define fields for signup and registration serializers

---

events/middleware.py
events/tests/test_auth.py
linkedevents/settings.py

This PR adds a middleware which will add the no-cache headers for all authenticated requests.

LINK-1578 | Add no-cache headers for all authenticated requests

---

registrations/api.py
registrations/tests/test_signup_get.py
registrations/tests/test_signup_group_get.py

Adds the `list` action and filtering by certain parameters to the `signup_group` endpoint. The filtering parameters and logic are shared between the `signup_group` and `signup` endpoints.
[LINK-1075](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1075)
[LINK-1075]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1075, part 4 | List signup groups

---

events/models.py
events/signals.py
linkedevents/settings.py
registrations/utils.py

- Makes it possible to define the `DEFAULT_FROM_EMAIL` using an environment variable. The main purpose of the variable will be to define a "noreply" address.
- Makes code where the noreply address has been determined individually use a common utility function for getting the address.
- The utility function will fall back to `Site.objects.get_current().domain` if `settings` do not have an address value.
[LINK-1451](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1451)
[LINK-1451]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1451 | Add env variable for noreply email address

---

registrations/permissions.py
registrations/tests/test_registration_get.py

Allow also anonymous users to get single registration. There will be another PR to check fields that only admin users will see.  At the moment `created_by`, `last_modified_by` and `registration_user_accesses` fields are only for the admin users
[LINK-1576](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1576)
[LINK-1576]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1576 | Allow anonymous user to retrieve a registration

---

registrations/api.py
registrations/tests/test_registration_delete.py
registrations/tests/test_registration_post.py
registrations/tests/test_registration_put.py
registrations/tests/test_send_message.py
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_group_delete.py
registrations/tests/test_signup_put.py

Registrations, signups and signup groups will now use only their own permissions - data source edit permissions will not be used by the registrations endpoints.
[LINK-1554](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1554)
[LINK-1554]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Don't use DataSourceResourceEditPermission in the registrations API

---

events/tests/test_auth.py
helevents/models.py
helevents/tests/conftest.py
helevents/tests/test_gdpr_api_delete.py
helevents/tests/test_gdpr_api_get.py
helevents/utils.py
linkedevents/settings.py
linkedevents/urls.py
registrations/models.py
requirements.in
requirements.txt

Adds the [Helsinki Profile GDPR API ](https://github.com/City-of-Helsinki/helsinki-profile-gdpr-api/) to the project, and makes it possible for a user to query and delete their own GDPR data. It has been determined that at this point the data stored in the `helevents_user`, `registrations_signup` and `registrations_signup_group` tables are the ones to be subject to querying and deleting like this.
[LINK-1011](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1011)
[LINK-1011]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1011 | Helsinki Profile GDPR Endpoints

---

events/api.py
events/auth.py
helevents/models.py
helevents/serializers.py
helevents/tests/test_user_get.py
registrations/api.py
registrations/models.py
registrations/serializers.py
registrations/tests/test_registration_get.py

- Allow admin and registration admin users to see `created_by`, `last_modified_by` and `registration_user_accesses` fields
- `has_registration_user_access` field which is set to true if current user is strongly identificated and is in registration_user_accesses
[LINK-1576](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1576)
[LINK-1576]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1576 | Registration admin fields

---

events/importer/kulke.py
helevents/service_tasks/hourly_tasks.sh

Kulke importer works well enough to be enabled once again.
Commented out course import in code level to avoid any accidental course imports (since we're not quite sure if it works as intended).
Refs LINK-1580

LINK-1580: Enable hourly kulke import, disable kulke course import

---

registrations/api.py
registrations/tests/test_send_message.py

Split `_get_messages` method to `_get_message_signups` and `_get_messages` methods.
- `_get_message_signups` returns all the signups to which the email message will be sent
- `_get_message` generates messages for each of those signups 
Return value from `_get_message_signups` is used when serializing response for send_message action
[LINK-1608](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1608)
[LINK-1608]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1608 | Return signups also when sending message to signup group

---

registrations/api.py
registrations/permissions.py
registrations/serializers.py
registrations/tests/test_registration_post.py
registrations/tests/test_signup_group_patch.py
registrations/tests/test_signup_patch.py
registrations/tests/test_signup_put.py

Makes the following changes for updating sign-ups:
- A registration user (`RegistrationUserAccess`) is only allowed to update the `presence_status` field and nothing else.
- The user who created the sign-up is allowed to update all other data except `presence_status`.
A superuser or a registration admin is still allowed to update all data of a sign-up.
[LINK-1429](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1429)
[LINK-1429]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1429 | Permissions for signup presence status

---

locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
registrations/models.py
registrations/templates/cancellation_confirmation.html
registrations/templates/message_to_signup.html
registrations/templates/signup_confirmation.html
registrations/templates/signup_confirmation_to_waiting_list.html
registrations/templates/signup_list_rights_granted.html
registrations/templates/signup_transferred_as_participant.html
registrations/tests/test_send_message.py

Show event name in the email which is sent via send_message endpoint.
Also add missing edit signup link to the email message and add unit tests to make sure that is really exists.
[LINK-1472](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1472)
[LINK-1472]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1472 | Show event name in the email which is sent via send_message endpoint

---

events/api.py
events/auth.py
events/tests/test_auth.py
events/tests/test_event_post.py
events/tests/test_permissions.py
helevents/models.py

When creating an event the publisher field is not required. If the publisher field is not sent it will default to:
- users organization, 
- data sources owner when api key is used or 
- to the external organization when external user sends the event. 
There was an issue where the external organization was set as the publisher if the publisher was not in the event data. The fix is to set the default external organization only if an external user sends the data and the publisher is missing.

LINK-1615 | Fix external organisation set as publisher

---

events/signals.py
linkedevents/settings.py
linkedevents/tests/test_sentry.py

Currently, a user's full name and email address are logged to Sentry if an exception involves a `User` instance. It was decided that we should not log those but instead just the user's `username` and that's what has been implemented in this PR.
[LINK-1620](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1620)
[LINK-1620]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1620 | Log only a user's username to Sentry

---

linkedevents/apps.py
linkedevents/migrations/0001_remove_allauth_remnants.py

In commit bf155e2 the dependency to django-allauth was removed. But that commit didn't clean allauth stuff away from the database. This commit does that.
A migration file handles the cleaning. The migration file is added to the linkedevents app.

LINK-1543 | Remove stale allauth tables and contenttypes

---

registrations/api.py
registrations/tests/test_registration_head.py
registrations/tests/test_seatsreservation_head.py
registrations/tests/test_send_message.py
registrations/tests/test_signup_group_head.py
registrations/tests/test_signup_head.py

OWASP states that only necessary HTTP verbs / methods should be allowed for an API. The HEAD method is seen as such for the registrations API and will not be allowed after these changes.
To ensure a semantically correct HTTP response status code (405), the method has been prevented in the ViewSets instead of in the permissions.
[LINK-1587](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1587)
[LINK-1587]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1587 | Prevent the HEAD method for registrations API

---

events/api.py
events/models.py
events/tests/test_event.py
events/tests/test_event_post.py
events/tests/test_event_put.py

Previously Event.save did m2m validation on keywords, but that does not work as intended, as serializers update m2m relations after the model save is done. Therefore an event with deprecated keywords can not be updated, as the model cannot be saved before the deprecated keywords are  removed. Also validation logic belongs to the serializer, not the model save.
Ref https://helsinkisolutionoffice.atlassian.net/browse/LINK-1605

Move dysfunctional deprecated kw validation from model.save to serializer

---

events/importer/base.py
events/importer/harrastushaku.py
events/importer/helmet.py
events/importer/kulke.py
events/importer/lippupiste.py
events/importer/matko.py
events/importer/mikkelinyt.py
events/importer/tprek.py
events/importer/yso.py
events/management/commands/event_import.py
helevents/service_tasks/daily_tasks.sh
helevents/service_tasks/hourly_tasks.sh
linkedevents/urls.py

This PR disables haystack's `RealtimeSignalProcessor` for all `event_import` calls in `hourly_tasks.sh` and `daily_tasks.sh`.
Also includes some additional improvements:
- Add default timeouts to all `request.get` calls in importers
- Replace deprecated `django.conf.urls.url`

LINK-1629 | Improve cron job performance

---

registrations/api.py
registrations/tests/test_send_message.py

When sending a mass email to all signups, the email will now be sent to only those who have the status "attending". Wait-listed signups shouldn't get the email in this case.
[LINK-1618](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1618)
[LINK-1618]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1618 | Mass Email to Attending Signups Only

---

events/importer/base.py
events/importer/enkora.py
events/importer/espoo.py
events/importer/harrastushaku.py
events/importer/helmet.py
events/importer/kulke.py
events/importer/lippupiste.py
events/importer/matko.py
events/importer/osoite.py
events/importer/sync.py
events/importer/tprek.py
events/importer/util.py
events/importer/yso.py

This PR reduces the amount of memory used by `osoite.py` importer. Using an iterator makes sure the queryset does not cache it's result (which is not needed in this case).
Tested the importer locally. Memory consumption went from roughly 2,3 GB to 1,3 GB. Locally the change had hardly any effect on processing time.

LINK-1629 | Reduce memory footprint of osoite.py

---

registrations/models.py
registrations/signals.py
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_group_delete.py

When a waitlisted `SignUp` or a `SignUpGroup` that has only waitlisted signups is deleted, don't change the `attendee_status` of the first waitlisted signup to `attending`.
[LINK-1637](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1637)
[LINK-1637]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1637 | Don't move waitlisted to attending on waitlisted deletion

---

events/api.py
events/utils.py
registrations/serializers.py
registrations/tests/test_registration_post.py
registrations/tests/test_registration_put.py
registrations/tests/test_signup_group_post.py
registrations/tests/test_signup_group_put.py
registrations/tests/test_signup_post.py
registrations/tests/test_signup_put.py

- Move `clean_text_fields` method to `events/utils` to avoid circular imports 
- Sanitize `Signup`, `SignupGroup` and `Registration` serializers text fields
[LINK-1589](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1589)
[LINK-1589]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1589 | Use bleach to clean registration related text fields

---

events/api.py
events/tests/test_keyword_get.py

free_text filter was originally probably accidentally inserted in the middle of an unrelated if/else clause, breaking filtering of deprecated events.
Ref LINK-1654

Relocate free_text filter

---

README.md
docker/django/docker-entrypoint.sh
events/management/commands/add_helsinki_audience.py
events/management/commands/create_languages.py
events/tests/management/test_create_languages.py

This PR adds translations for keywords added by `add_helsinki_audience` and also for `Language` instances which currently exist in production. For `Language` objects a separate new script `create_languages` is added which can create all instances which currently exists in production and is also able to update translations. For language names I tried to use translations provided by Django, but unfortunately they were not perfect so I decided to hard code the values in the script.
Translations in this PR have already been done in production, but for any new or existing environment these are missing and therefore they should also be part of the codebase.

LINK-1612 | Add translations for objects

---

events/importer/harrastushaku.py
events/tests/importers/test_harrastushaku.py

If the end time is before start time interpret that as a overnight event.
Refs LINK-1638

LINK-1638 | Make harrastushaku importer support overnight events

---

events/models.py
events/tests/test_notifications.py

Do not send the notification considering child events of recurring super events. 
Also do not send draft notifications from events created by admins.
Refs LINK-1564 LINK-1633

LINK-1564 | Send only parent draft event created notification

---

events/tests/test_event_post.py
events/tests/test_event_put.py
requirements-dev.in
requirements-dev.txt

A couple tests are temporarily broken because of DST stuff. Should start working next week... or after this fix. Added xfail tests for the DST stuff; might have an actual DST related bug hiding here.

Add pytest-freezer (freeze time marker), fix broken tests

---

events/api.py
events/tests/test_api.py

Using unescaped user input (via query strings) in regexes causes errors and is a security vulnerability. This PR escapes the input before using it in regex.
Also wrote some unit tests for `_terms_to_regex`. Apparently, the OR operator is completely busted, which I'm not going to address in this PR, so marked the OR cases with xfail.

LINK-1593: Escape regex input

---

locale/fi/LC_MESSAGES/django.po

Use the word 'jono' instead of 'varasija' in Finnish translations to ensure back-end translations better match with recent front-end translation changes. This will be especially necessary for the upcoming registration signups XLSX export (LINK-1658).
[LINK-1670](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1670)
[LINK-1670]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1670 | Use the word 'jono' instead of 'varasija' in Finnish translations

---

config_dev.toml.example
linkedevents/settings.py

ref https://helsinkisolutionoffice.atlassian.net/browse/LINK-1657
Originally was intending to add a separate env var EMAIL_TO_CONSOLE and raise ImproperlyConfigured if none of MAILGUN_API_KEY, EMAIL_TO_CONSOLE or DEBUG was set, but that broke management.py.

Use console email backend if API_MAILGUN_KEY is not set

---

events/migrations/0035_add_n_events_to_keyword.py
events/migrations/0036_add_n_events_to_place.py
events/models.py
events/tests/test_event.py

Especially in case of soft deletion by importers
save(update_fields=[...]) would be called, which leaves last_modified_time untouched. This commit changes the updating of last_modified_time as opt-out. The last_modified_time is not updated when n_events is updated.

Ensure last_modified_time is updated when an event is saved

---

events/importer/kulke.py
events/models.py
events/tests/importers/test_kulke.py
events/tests/test_models.py

If the event is marked as deleted (soft deleted) and is found in elis data in the kulke importer, it's going to be restored and marked as not deleted.
Refs LINK-1614

LINK-1614 | Enable restoring elis events in kulke importer

---

events/api.py
registrations/api.py
registrations/models.py
registrations/tests/test_registration_put.py

At the moment registration admins are not allowed to edit registrations. The reason is that `CanAccessRegistration` `has_object_permission` method calls `Event.can_be_edited_by` instead of `Registration.can_be_edited_by` when `RegistrationViewSet` `perform_create` or `perform_update` methods check permissions by using `self.check_object_permissions(self.request, event)`. 
Fix this by moving event data source permission check to create method of RegistrationSerializer.
Also make event read_only field when updating the registrations. In that case there is no need for the event data source permissions check anymore.
[LINK-1690](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1690)
[LINK-1690]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1690?atlOrigin=eyJpIjoiNWRkNTljNzY …

LINK-1690 | Allow registration admins to update registration

---

registrations/serializers.py
registrations/tests/test_signup_get.py
registrations/tests/test_signup_group_get.py

At the moment Linked Registration UI doesn't know is the signup or signup group created by the current user. This is information is needed to grant permissions to edit signup or signup group created by the current user. Add `is_created_by_current_user` field to signup and signup group serializers to provide that information
[LINK-1687](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1687)
[LINK-1687]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1687 | is_created_by_current_user field to signup serializer

---

registrations/api.py
registrations/models.py
registrations/serializers.py
registrations/tests/test_models.py
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_patch.py
registrations/tests/test_signup_put.py

Prevents deleting or removing through editing the only responsible person of a `SignUpGroup`. Such a person is technically a `SignUp` with `responsible_for_group=True`.
[LINK-1660](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1660)
[LINK-1660]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1660 | Prevent removing the only responsible person of a group

---

registrations/api.py
registrations/migrations/0026_unique_seat_reservation_and_attendee_status_index.py
registrations/serializers.py
registrations/tests/test_signup_group_post.py
registrations/tests/test_signup_post.py
registrations/tests/test_signup_serializer.py

Use `bulk_create` when creating multiple signups and their protected data in the `signup` and `signup_group` endpoints. 
Additionally, check the attendee and waiting list capacities only once instead of for each signup separately.
[LINK-1707](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1707)
[LINK-1707]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1707 | Use bulk_create when creating multiple signups

---

registrations/api.py
registrations/tests/test_signup_get.py

To ensure that the front-end gets the correct paginated queryset when displaying a paginated signups table to the end-user, ordering by first and last name is added to `SignUpViewSet`.
[LINK-1731](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1731)
[LINK-1731]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1731 | Order signups queryset by first and last name

---

.dockerignore
README.md
config_dev.env.example
linkedevents/settings.py

Since the file is not and never was a toml file by content.
As this may affect your local development setup rather unexpectedly, FYI also 
* @jorilindell
* @harriris-vincit 
* @City-of-Helsinki/ratkaisutoimiston-frontend

Rename config_dev.toml -> config_dev.env

---

events/tests/test_keywordset_put.py
events/tests/test_organization_api.py
locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
registrations/exports.py

Adds info texts about data protection and the possibility of the signup and the contact person information being for different persons.
Also adds missing Finnish and Swedish translations for the phrase "Registered persons" and updates the translations as a whole.
[LINK-1726](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1726)
[LINK-1726]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1726 | Signups Excel export info texts

---

events/api.py
events/tests/test_api.py

LINK-1716 | Use localdate when fetching dissolved orgs through api

---

events/api_pagination.py

Large values seems to be unused so the page size for LargeResultsSetPagination is limited to the default page size.

LINK-1728 | lower LargeResultsSetPagination.max_page_size

---

registrations/api.py
registrations/models.py
registrations/permissions.py
registrations/serializers.py
registrations/tests/test_registration_get.py
registrations/tests/test_send_message.py
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_get.py
registrations/tests/test_signup_group_delete.py
registrations/tests/test_signup_group_get.py
registrations/tests/test_signup_group_patch.py
registrations/tests/test_signup_group_put.py
registrations/tests/test_signup_patch.py
registrations/tests/test_signup_put.py
registrations/tests/test_signups_export.py

Allows organization admins (also known as event admins or regular admins) to view, edit and delete registrations and signups if the registration is created by them.
Creation of new registrations and signups has already been possible for them, and no changes have been done for that functionality.
[LINK-1741](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1741)
[LINK-1741]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1741 | Organization admins can manage registrations & signups created by them

---

events/api.py
events/tests/test_event_images_v1.py

This PR fixes an internal server error being thrown instead of returning a validation error when an external user (a user which doesn't belong to an organization) sets an arbitrary organization. Since the user doesn't belong to any organization the publisher field should be left blank.

LINK-1727 | Fix internal server error on image upload when external user sets an arbitrary publisher

---

requirements.txt

Helsinki address importer is currently failing. This has been fixed in [django-munigeo 0.3.10](https://github.com/City-of-Helsinki/django-munigeo/releases/tag/release-0.3.10).

Upgrade django-munigeo to 0.3.10

---

linkedevents/settings.py
requirements-dev.txt
requirements.in
requirements.txt

Bump django-heluser. Also bump all other libraries as well and remove pinned restriction from `drf-oidc-auth`.

LINK-1790 | Update django-heluser package

---

registrations/serializers.py
registrations/tests/test_registration_get.py

Add signup_url field to registration serializer so the user knows where the signup form is located
Slack discussion: https://helsinkicity.slack.com/archives/C02L127FC/p1701686920598549
[LINK-1797](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1797)
[LINK-1797]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1797 | Add signup url to registration serializer

---

.github/workflows/ci.yml
.pre-commit-config.yaml
README.md
commitlint.config.js

From now on, all new commit messages must adhere to the [conventional commits spec](https://www.conventionalcommits.org/en/v1.0.0/) and their max line length is limited to 72 characters. The rules are enforced with [commitlint](https://commitlint.js.org/#/), which is run as a pre-commit hook and also as a stage in the GitHub CI pipeline.

Start using conventional commits

---

events/signals.py
events/tests/test_notifications.py

Currently an email notification is sent to all superusers about every new user. Now that we have outside users and registration users, we most probably don't want to be sending those notifications anymore. The notification is just disabled for now, but should be completely removed later if there is no use for it.

Disable user created email notification

---

README.md
events/models.py
events/signals.py
events/tests/test_notifications.py
linkedevents/settings.py
locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
registrations/api.py
registrations/models.py
registrations/notifications.py
registrations/signals.py
registrations/templates/event_cancellation_confirmation.html
registrations/tests/test_event_cancellation_notification.py
registrations/tests/test_models.py
registrations/tests/test_send_message.py
registrations/utils.py
requirements.in
requirements.txt

When an event is cancelled (`Event.event_status` is set to `EventCancelled`), an email notification about the cancellation will be sent to the contact persons of all the related signups and signup groups.
Due to the possibility of large amounts of emails being sent in the worst case, the `django-mailer` package is added and taken into use to queue the emails for later sending (which can be easily further controlled in terms of sending delay and batch size, for example). Using `django-mailer` also allows non-blocking emailing so this should bring a general improvement too for code that uses the Django emailing functions.
Scheduling for the `django-mailer` management commands `send_mail` (send queued emails), `retry_deferred` (retry failed emails) and `purge_mail_log` (clean successfully …

LINK-1718 | Add email notification to contact persons on event cancellation

---

locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
registrations/notifications.py
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_group_delete.py
registrations/tests/test_signup_group_post.py
registrations/tests/test_signup_post.py

The signup cancellation and confirmation templates expected a username (the contact person's first name) to always exist which resulted in a phrase with either an empty name or "None" as the name being shown in the HTML email templates. This PR fixes the issue by checking if a name exists and showing a suitable phrase based on that.
[LINK-1837](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1837)
[LINK-1837]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1837 | Signup confirmation template texts without username

---

helevents/tests/test_gdpr_api_delete.py
helevents/utils.py

In gdpr api delete operation, null  users's event user fields when the `user_email` field matches to user's email.
Refs LINK-1644

LINK-1644 feat: add event user data removal to gdpr delete

---

events/importer/base.py
events/importer/utils.py

E.g. on an hourly cronjob, there were 14.7k lines of logs generated. These two logging lines generated approximately 13.7k lines. Which is about 93% of the total lines.
These aren't very informative either, so decided to remove them. It's a lot of noise.

feat: remove spammy debug logs from importers

---

events/tests/test_auth.py
helevents/models.py
linkedevents/settings.py
registrations/tests/test_registration_get.py
registrations/tests/test_signup_get.py
registrations/tests/test_signup_group_get.py
registrations/tests/test_signup_group_patch.py
registrations/tests/test_signup_group_put.py
registrations/tests/test_signup_patch.py
registrations/tests/test_signup_put.py
registrations/tests/test_signups_export.py

Tunnistamo returns amr-claim as a string. Keycloak return the claim as a list of strings, which is according to specification. This changes the logic in linked events to expect a list for User.token_amr_claim.

LINK-1382 | feat: support keycloak in User.token_amr_claim

---

linkedevents/settings.py
registrations/tests/test_registration_get.py
registrations/tests/test_signup_get.py
registrations/tests/test_signup_group_get.py
registrations/tests/test_signup_group_patch.py
registrations/tests/test_signup_group_put.py
registrations/tests/test_signup_patch.py
registrations/tests/test_signup_put.py
registrations/tests/test_signups_export.py

KeyCloak uses "suomi_fi" in the amr claim value instead of the current default "heltunnistussuomifi". This PR changes the default value to enable strong identification to work with the KeyCloak authentication with the default setting.
[LINK-1851](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1851)
[LINK-1851]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: use the correct value for KeyCloak suomi.fi method

---

linkedevents/settings.py

The `django-mailer` uses a lockfile to ensure that an email is not sent twice. By default, the path of that lockfile is the current working directory which seems to cause a permission issue with LE cron jobs that try to create the lockfile. Since `django-mailer` also has a DB-based lock that is more reliable than the file-based one when available, this PR disables the file-based lock completely.
[LINK-1852](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1852)
[LINK-1852]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: disable file-based lock for django-mailer

---

helevents/tests/test_gdpr_api_delete.py
helevents/utils.py
linkedevents/settings.py

The user deletion through the gdpr api deletes user from the database and its data. This is problematic since the users are shared by two services (events and registrations).
This disables the user data deletion for now via the api to avoid unwanted user deletions.
Deletion request returns 403 (forbidden).

Disable user deletion through GDPR api

---

locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
registrations/exports.py

At the moment the signups XLSX export displays only the contact person's email and phone number. Add also signup's phone number to the export and rename contact person's email and phone number column headers.
[LINK-1885](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1885)
[LINK-1885]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1885 | Add Signup's Phone Number to XLSX Export

---

.dockerignore

Fixes broken build due to the new `web_store` app not being mentioned in the `.dockerignore` file.

fix: whitelist web_store in the dockerignore file

---

events/importer/espoo.py
events/tests/importers/test_espoo.py

This does complicate the importer slightly as Image object does not have origin_id field and a decision was made to not add one. Support has been added to depend on custom field for mapping, although the default behaviour is still:
(hel) origin_id <-> (espoo) id
For images we use simply
(hel) url <-> (espoo) url
It's important to note that url is not unique, so imported events may
end up linking to same hel Image even if they link to different Images
in the Espoo API.
Ref LINK-1871

feat: support images in Espoo importer

---

registrations/serializers.py
registrations/tests/test_signup_group_post.py
registrations/tests/test_signup_post.py

The `create_payment` kwarg will no longer be used in `SignUp` init in the `CreateSignUpSerializer.create_signups` method. Giving the kwarg resulted in a 500 internal error, and it is not needed at all in the said method as payment creation is handled by `SignUpSerializer.create` instead.
[LINK-1896](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1896)
[LINK-1896]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: don't use create_payment in create_signups

---

events/models.py
events/tests/test_models.py
events/tests/test_notifications.py
locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
notifications/exceptions.py
notifications/models.py
notifications/tests/test_utils.py
notifications/utils.py
registrations/models.py
registrations/notifications.py
registrations/signals.py
registrations/tests/test_event_cancellation_notification.py
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_group_delete.py
registrations/tests/test_signup_group_post.py
registrations/tests/test_signup_post.py

Adds email notifications for signups that have been made for recurring super events. Also adds an event cancellation notification for the case where a sub event of a recurring super event is cancelled (the registration will have been done to the super event, but not to the sub event in this case). 
[LINK-1811](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1811)
[LINK-1811]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1811 | Email Notifications for Recurring Event Signups

---

events/api.py
events/tests/test_event_get.py
helevents/templates/rest_framework/event_list.html

Adds six new ordering filters / sorting options for the `event` endpoint:
- `enrolment_start_time`: sorts by `event.enrolment_start_time` only.
- `enrolment_end_time`: sort by `event.enrolment_end_time` only.
- `registration__enrolment_start_time`: sorts by `event.registration.enrolment_start_time` only.
- `registration__enrolment_end_time`: sort by `event.registration.enrolment_end_time` only.
- `enrolment_start`: sorts primarily by `event.registration.enrolment_start_time`, but will fall back to using `event.enrolment_start_time` if `registration`or `registration.enrolment_start_time` is NULL. If both the event's and registration's `enrolment_start_time` are NULL, the event will be placed at the end of the sorted list (doesn't matter if ascending or descending direction is used).
- …

feat: event ordering and filtering by enrolment start and end time

---

registrations/management/commands/anonymize_past_signups.py
registrations/models.py
registrations/tests/test_commands.py
registrations/tests/test_models.py

- Use enrolment_end_time value of registration in anonymization if it's later than end_time of event.
- Set extra_info field as None in anonymizaation
[LINK-1916](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1916)
[LINK-1915](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1915)
[LINK-1916]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LINK-1915]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1915, LINK-1916 | Fine-tune anonymization

---

locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
registrations/api.py
registrations/exceptions.py
registrations/models.py
registrations/notifications.py
registrations/serializers.py
registrations/templates/_open_payment_link_button.html
registrations/templates/common_signup_confirmation.html
registrations/tests/management/test_mark_payments_expired.py
registrations/tests/test_models.py
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_group_delete.py
registrations/tests/test_signup_group_post.py
registrations/tests/test_signup_post.py
registrations/tests/test_web_store_webhook_post.py
registrations/tests/utils.py
registrations/utils.py
web_store/tests/utils.py

Adds two new features related to Talpa payments:
- After a payment / Talpa order has been created for a signup or signup group, an email confirmation with a payment link will be sent to the contact person.
- Signing up to the waiting list of a paid event is now possible. Previously only attending signups were allowed. When a waitlisted signup is moved to be an attending participant, a payment is created for them and the payment link is emailed to the contact person.
[LINK-1881](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1881)
[LINK-1881]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1881 | Send Payment Link to Contact Person, Allow Waitlisted Signups for Paid Events

---

events/api.py
registrations/admin.py
registrations/models.py
registrations/tests/test_admin.py
registrations/tests/test_registration_put.py
registrations/tests/utils.py

Send invitation to registration user access email also when is_substitute_user values is changes. 
Move logic to send invitation to signals to avoid duplicate code in admin side and RegistrationViewSet
[LINK-1926](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1926)
[LINK-1926]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1926 | send invitation is is_substitute_user is changed

---

events/importer/espoo.py

Avoids duplicate sentry logs due to random order caused by using a set.

fix: use sort in error log

---

helevents/tests/test_gdpr_api_delete.py
locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
notifications/tests/test_utils.py
registrations/api.py
registrations/management/commands/mark_payments_expired.py
registrations/models.py
registrations/notifications.py
registrations/signals.py
registrations/tests/test_models.py
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_group_delete.py
registrations/utils.py
web_store/clients.py
web_store/order/enums.py
web_store/payment/clients.py
web_store/tests/order/test_web_store_order_api_client.py
web_store/tests/payment/test_web_store_payment_api_client.py

Automatically do a Talpa refund request when cancelling a signup or a signup group that has an unrefunded payment.
[LINK-1880](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1880)
[LINK-1880]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1880 | Automatically Refund Signup Payments

---

events/permissions.py
events/tests/test_organization_api.py

It was not possible for a user with both a financial admin and an organization admin permissions to create or update an organization if the payload contained web store merchant or account data. This PR fixes the issue.
[LINK-1965](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1965)
[LINK-1965]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1965 | Financial admin with admin role can POST or PUT organization data

---

events/tests/test_organization_api.py
helevents/tests/test_admin.py
registrations/models.py

When a `WebStoreMerchant` is saved and the data that also exists in Talpa has not been changed, do not do an unnecessary update request to the Talpa API.
[LINK-1969](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1969)
[LINK-1969]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1969 | Don't update merchant in Talpa if data has not changed

---

events/tests/test_organization_api.py
registrations/serializers.py
registrations/tests/test_registration_post.py

Changes the `WebStoreMerchantSerializer.merchant_id` field to have `read_only=True`. This is because the value is set automatically based on the Talpa API response and should not be editable through the API.
[LINK-1968](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1968)
[LINK-1968]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1968 | Make merchant_id read-only

---

registrations/management/commands/mark_payments_expired.py
registrations/utils.py
web_store/order/clients.py
web_store/tests/order/test_web_store_order_api_client.py

Fixes unpaid order cancellation. The request path and header were wrong in the Talpa Order Experience API client, and the system was not passing the user UUID as string at all to the client or the API in the request header.
[LINK-1994](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1994)
[LINK-1994]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1994 | Fix signup unpaid order cancellation

---

registrations/models.py
registrations/tests/management/test_mark_payments_expired.py
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_group_delete.py

Immediately mark a signup with a newly-created payment as "attending" when they are transferred from the waiting list to attending for a registration that requires a payment. This is what normally happens when signup is created as attending.
[LINK-1999](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1999)
[LINK-1999]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1999 | Mark transferred signup with payment as attending

---

locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
registrations/notifications.py
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_group_delete.py
web_store/tests/order/test_web_store_order_api_client.py
web_store/tests/payment/test_web_store_payment_api_client.py

Signup cancellation notifications for recurring events were missing texts for cases where a payment is cancelled or refunded. This PR adds them.
[LINK-2005](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2005)
[LINK-2005]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2005 | Add missing recurring event payment notifications

---

events/importer/enkora.py
events/tests/importers/test_enkora.py

Changes to date interval used for importing places and courses, as well the yso-mappings as required by liikunta.hel.fi. Agreed with KUVA/Liikunta

fix: change Enkora importer date interval and yso mappings

---

registrations/management/commands/mark_payments_expired.py
registrations/models.py
registrations/signals.py
registrations/tests/test_models.py
registrations/tests/test_registration_put.py
registrations/utils.py

When a registration's maximum attendee capacity is increased, move as many waitlisted signups to attendees as possible.
[LINK-1996](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1996)
[LINK-1996]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1996 | Move signups to attending on attendee capacity increase

---

events/api.py
events/models.py
registrations/models.py
registrations/signals.py
registrations/tests/test_event_cancellation_notification.py
registrations/tests/test_models.py

This PR implements the following three requirements:
- When an event that has a registration is soft-deleted or cancelled, the related registration's signups and signup groups need to be cancelled and their contact persons notified. 
- When a sub-event of a super event is soft-deleted or cancelled, only event cancellation notifications should be sent and the signups should remain if the registration is linked to the super event only. 
- Payments should be cancelled or refunded in case signup and signup groups cancellations are performed.
[LINK-1799](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1799)
[LINK-1799]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1799 | Cancel signups on event deletion or cancellation

---

events/api.py
events/permissions.py
events/tests/conftest.py
events/tests/test_organization_api.py

Makes it possible to get all active merchants and accounts for an organization through new action endpoints that are under the organization detail endpoint. Since merchants and accounts are meant to be inherited from higher organization levels, the new endpoints search for them from ancestor organizations, returning results from the first ancestor that has them.
[LINK-2043](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2043)
[LINK-2043]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2043 | Action endpoints for getting merchants and accounts

---

events/api.py
events/tests/conftest.py
events/tests/test_event_get.py

`keyword_set_AND`, `keyword_set_OR `and `keyword_OR_set ` filters did not search from audiences when other keyword filters did. This adds lookups for audiences for those aforementioned filters
Refs LINK-1933

feat(events-api): match audience in keyword_* filters

---

data_analytics/serializers.py
data_analytics/tests/test_event_get.py
data_analytics/tests/test_place_get.py
linkedevents/serializers.py

- Adds "name" and the non-translated field "address_locality" to `DataAnalyticsPlaceSerializer`.
- Adds "name" to `DataAnalyticsEventSerialiazer`.
- Ensures that `TranslatedModelSerializer` is used with such data analytics serializers that expose translated fields.
- Fixes an issue with `TranslatedModelSerializer` where it exposed all of the translated fields even if they weren't given in the sub-classed serializer's `fields`.
[LINK-2073](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2073)
[LINK-2073]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2073 | Translated fields to data analytics API

---

registrations/models.py
registrations/tests/test_signup_group_post.py
registrations/tests/test_signup_post.py
registrations/tests/test_utils.py
registrations/tests/utils.py
registrations/utils.py

Adds a "lang" GET parameter after the Talpa checkout URLs.
[LINK-2080](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2080)
[LINK-2080]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2080 | Add lang parameter to checkout URLs

---

events/management/commands/remove_unused_permissions.py
events/tests/management/test_remove_unused_permissions.py
linkedevents/settings.py

Command for removing expired admin and registration user access permissions. Env variables are also added to allow controlling the expiration thresholds.
[LINK-1808](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1808)
[LINK-1808]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1808 | Command for removing expired admin permissions

---

registrations/models.py
registrations/tests/test_event_cancellation_notification.py
registrations/tests/test_models.py
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_group_delete.py
registrations/utils.py
web_store/payment/clients.py
web_store/tests/payment/test_web_store_payment_api_client.py

For refunds, always use the `order/refund/instant` endpoint. It has turned out that the endpoint under the Payment Experience API should not be used by client services anymore.
[LINK-2078](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2078)
[LINK-2078]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2078 | Always use the order refund Talpa endpoint

---

events/api.py
events/tests/test_event_get.py

Catches GDALException when querying events with bad srid. Previously was causing 500. Now returns 400.
Refs LINK-1842

fix: catch gdal error in events api

---

registrations/models.py
registrations/utils.py

Ensures that if the contact person's service language is `None`, the value `fi` will be used as the default language for the Talpa checkout.
LINK-2084

LINK-2084 | Ensure correct default for checkout language

---

data_analytics/serializers.py
data_analytics/tests/test_place_get.py

Ensures that coordinates are returned using `DEFAULT_SRS` from the data analytics API.
LINK-2096

LINK-2096 | Use GeoModelSerializer in analytics API

---

registrations/tests/test_utils.py
registrations/utils.py

Talpa uses the Helsinki timezone when checking `lastValidPurchaseDateTime`. This PR ensured that the same timezone is used when sending the timestamp to the Talpa Order Experience API.
Note to those who test this change: there is a known bug in the Talpa checkout UI that makes the "Time left for purchase" display to show a value such as "23:59:59" instead of "48:00:00". This is to be fixed by the Talpa devs.

fix: use correct timezone for lastValidPurchaseDateTime

---

data_analytics/api.py
data_analytics/serializers.py
data_analytics/tests/test_data_source_get.py
data_analytics/urls.py

Adds an endpoint for `DataSource` objects to the data analytics API. The field `has_api_key` can be used to determine if the data source is used against the API for bringing events.
LINK-2097

LINK-2096 | Add data_source endpoint to analytics api

---

linkedevents/settings.py
linkedevents/tests/conftest.py
linkedevents/tests/test_sentry.py

Makes Sentry client use `EventScrubber` to scrub sensitive information before it is sent to the Sentry server.
The unit test is split into three different ones because it seems that only at most seven variables are recorded into the Sentry event.
[LINK-1645](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1645)
[LINK-1645]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1645 | Scrub sensitive data through sentry_sdk

---

events/importer/enkora.py

- Changed tprek-id for "Latokartanon liikuntahalli" due to apparent change in source
- "ELIXIA Ruoholahti / Kuntokeskus" (tprek:40101) can't be shown as the event location so created manual place mapping with the name "Kuntosali Ruoholahti, Itämerenkatu 21, 4.krs." and accompanying information
- "Perhetalo Unikko" place added as it doesn't exist in TPR
- Updated organization name to "Liikuntaan aktivointi" based on user feedback
- Added exception handling and error logging for timestamp processing during event import
- Added course ID to error logging for when an unrecognised place is encountered

Fix: Enkora importer places and timestamps

---

registrations/api.py
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_group_delete.py

Allows only admins to delete a signup or a signup group after an event has started.
[LINK-2103](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2103)
[LINK-2103]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2103 | Allow only admins to delete signups after event has started

---

events/api.py
events/tests/conftest.py
events/tests/test_event_get.py
linkedevents/tests/conftest.py

If no events were found, the filter caused a crash (TypeError, set.intersection needs values). This fixes the issue.
This also fixes another issue; this error was encountered with the query param `local_ongoing_OR_set=xxxxxxx`, which shouldn't even trigger the filter (according to the implementation) since it requires an ascending number at the end, starting from 1. E.g. `blabla_OR_set1=x,blabla_OR_set2=y` is valid.
There's also something terribly wrong with the regex that the ongoing OR set filters use. Apparently, this was encountered in https://github.com/City-of-Helsinki/linkedevents/commit/f581b16a2b9df1bf0f21a404f29e87a4766bee40, since there are tests marked as xfail for the function.
Added some test cases for the filter (there were none before), but marked them as xfail because the …

fix(events): fix error with x_ongoing_OR_set

---

events/api.py
events/tests/test_api.py
events/tests/test_event_get.py

Previously `_terms_to_regex` generated regex like this:
`(|\\|b|(|f|o|o|)|{|e|<|2|}|)|(|\\|b|(|b|a|r|)|{|e|<|2|}|)`
Now generates:
`(\\b(foo){e<2})|(\\b(bar){e<2})`
This should fix the issues with `x_ongoing_OR_set` filters.

LINK-2108: fix x_ongoing_OR_set filters

---

events/tests/test_permissions.py
events/tests/test_signals.py
registrations/tests/test_models.py
registrations/tests/test_signup_serializer.py

- Replaces `assertQuerysetEqual` method calls with `assertQuerySetEqual` as the former is removed in Django 5.1.
- Replaces `assertEquals` method calls with `assertEqual` as the former has been marked as deprecated.
- Removes the use of the deleted `no_test_audit_log` marker from one test.
[LINK-2121](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2121)
[LINK-2121]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2121 | Replace and remove some deprecated code from tests

---

events/importer/enkora.py
registrations/management/commands/mark_payments_expired.py
registrations/serializers.py
registrations/tests/test_seatsreservation_put.py
registrations/utils.py

To reduce issues raised by SonarCloud, the following have been done in this PR:
- Use `zoneinfo` instead of `pytz` in `registration.utils`, `registration.serializers`, `registration.commands.mark_payments_expired` and `events.importer.enkora`.
- Refactor the methods `SeatReservationSerializer.validate` and `SignUpSerializer.validate` to have smaller cognitive complexities.
[LINK-2124](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2124)
[LINK-2126](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2126)
[LINK-2124]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LINK-2126]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2126?atlOrigin=eyJpIjoiNWRkNTljNzYxN …

refactor: use zoneinfo instead of pytz, reduce complexity of two serializer methods

---

locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
registrations/templates/_message_to_signup_heading.html
registrations/templates/base_email.html
registrations/templates/cancellation_confirmation.html
registrations/templates/common_signup_confirmation.html
registrations/templates/event_cancellation_confirmation.html
registrations/templates/message_to_signup.html
registrations/templates/registration_user_access_invitation.html

Due to SonarCloud issues, the following two changes are done to registration's email notification templates:
- A `title` element with a proper value is added to all of them.
- The `lang` attribute is used in the `html` element of the base template. The value will be `linked_events_ui_locale` which is/should be equivalent to the service language of the contact person.
[LINK-2128](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2128)
[LINK-2129](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2129)
[LINK-2128]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LINK-2129]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …

feat: registration email template tweaks

---

helevents/tests/test_gdpr_api_delete.py
registrations/tests/management/test_delete_expired_seat_reservations.py
registrations/tests/test_registration_post.py
registrations/tests/test_registration_put.py

Make some tests in the `registrations` and `helevents` apps faster by using `django_capture_on_commit_callbacks` instead of `django_db(transaction=True)`.
[LINK-2130](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2130)
[LINK-2130]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2130 | Faster registration and GDPR delete transaction tests

---

registrations/serializers.py

Restores the use of `falsy_values` in the validation of mandatory fields when creating or updating a `SignUp`. Reasoning is given in the following comment of a previous PR: https://github.com/City-of-Helsinki/linkedevents/pull/967#discussion_r1734558582. 
Also fixes a typo in a comment in `registrations.serializers`.
LINK-2126

fix: safer mandatory fields validation

---

registrations/models.py
registrations/serializers.py
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_group_delete.py
registrations/tests/test_signup_group_post.py
registrations/tests/test_signup_post.py

Allows to sign up and create a Talpa payment with zero-priced customer group selections. A payment is also created when moving a waitlisted participant to the "attending" status if the participant has a customer group with a zero price.
[LINK-2131](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2131)
[LINK-2131]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2131: Allow payments for zero-priced customer groups

---

events/tests/test_organization_api.py
locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_group_delete.py
registrations/tests/test_signup_group_post.py
registrations/tests/test_signup_post.py
registrations/utils.py

Instead of including the technical error message returned by the Talpa API, make the Linked Events API return a more generic and user-friendly error message while still logging the error details that Talpa returned.
[LINK-2133](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2133)
[LINK-2133]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2133: User-friendlier web store API error message

---

events/api.py
events/tests/test_organization_api.py

Check ancestor organization admin permissions before returning web store accounts or merchants. The user must have the required permissions also in the upper organization levels.
[LINK-2135](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2135)
[LINK-2135]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2135: check ancestor perms for accounts and merchants

---

events/models.py
events/tests/test_feedback_form.py

Use the service's "noreply" email address as the "from" address instead of the email address given in the feedback. Also, include the email address given in the feedback in the body of the message that's sent to Linked Events support email. 
[LINK-1729](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1729)
[LINK-1729]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1729: Use noreply address for feedback

---

locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
registrations/notifications.py
registrations/tests/test_registration_user_access_invitation.py

Add info about the need to use the Suomi.fi identification method to the user access invitation email.
[LINK-2161](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2161)
[LINK-2161]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2161: Suomi.fi info text to user access invitation email

---

events/serializers.py
events/tests/test_event_post.py
events/tests/test_event_put.py
locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po

Duplicate event links / external links have resulted in a 500 internal error. This PR introduces validation that will result in a more user-friendly 400 validation error instead.
[LINK-2139](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2139)
[LINK-2139]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2139: Validation for duplicate event links

---

linkedevents/settings.py
registrations/utils.py

Change the default noreply address to `noreply-linkedevents@hel.fi`.
Related PR in DevOps for env-specific values: https://dev.azure.com/City-of-Helsinki/linkedevents/_git/linkedevents-pipelines/pullrequest/9420
[LINK-2164](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2164)
[LINK-2164]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2164: Change default noreply address

---

events/api.py
events/serializers.py
events/tests/test_event_get.py
events/tests/test_event_images_v1.py

Adds a new field `has_user_editable_resources` to event, image, place, keyword and keywordset endpoints. This allows the front-end to check before a form is saved if the related data source allows users to edit the given resource like an event.
[LINK-2163](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2163)
[LINK-2163]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2163: Add has_user_editable_resources field to API

---

registrations/api.py
registrations/tests/test_utils.py
registrations/tests/test_web_store_webhook_post.py
registrations/utils.py
web_store/clients.py
web_store/payment/clients.py
web_store/tests/payment/test_web_store_payment_api_client.py

Checks Talpa refund status from a new endpoint that is soon to be added to the Talpa Payment Exprerience API. This is needed for partial payment refunds as each refund will be their own instance with their own payment, and the older existing Talpa endpoint has supported fetching only the first refund's status (as partial refunds haven't actually been supported by Talpa before).
[LINK-2112](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2112)
[LINK-2112]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2112: Check refund status from a new endpoint

---

registrations/exports.py

Changes the registration Excel export's signups list to be ordered primarily by "attendee_status" and secondarily by the current ordering.
[LINK-2166](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2166)
[LINK-2166]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(registration): order XLSX primarily by attendee_status

---

data_analytics/admin.py
data_analytics/tests/test_admin.py

Hides Knox tokens from the Django admin site by unregistering the `knox.AuthToken` model. This is done because the `data_analytics.DataAnalyticsApiToken` model is used instead of the default model offered by the `django-rest-knox` package.
[LINK-2168](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2168)
[LINK-2168]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2168: Hide the Knox tokens section from the admin site

---

registrations/models.py
registrations/serializers.py
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_group_delete.py
registrations/tests/test_signup_group_post.py
registrations/tests/test_signup_post.py

Since Talpa doesn't currently support zero-priced payments or refunds, it was decided to revert the changes that made the API allow zero-priced signups. This will block making such payments and therefore there won't be problems with refunds either.
This reverts commit 9a3e03527b28777069591fe85d713dc5adba4808.
[LINK-2131](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2131)
[LINK-2131]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert "fix(registration): allow customer groups with zero price"

---

events/api.py
events/tests/test_event_post.py

Non-numeric event image IDs have resulted in a 500 internal server error. This PR implements a fix that makes the API return a  `serializers.ValidationError` instead.
[LINK-1529](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1529)
[LINK-1529]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1529: Give a ValidationError for invalid image id

---

events/api.py
events/tests/test_organization_api.py

It was decided that for account and merchant inheritance in the registration form (when creating a registration), it is not needed to check user permissions for the ancestor organization. Therefore, changes introduced in LINK-2135 are reverted by this PR.
This reverts commit 0510fcd109aab37fba4c109d63cade3e1c0e4b6b.
[LINK-2135](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2135)
[LINK-2135]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert "fix(regisration): check ancestor perms for accounts and merchants

---

.pre-commit-config.yaml

When using js commitlint config it requires version 9.13.0
and newer

chore(commitlint): use latest commitlint (9.18.0)

---

registrations/api.py
registrations/tests/test_signup_get.py

Order signups by the id in the signup endpoint to achieve correct ordering in the UI for the attendee list and waitlist listing.
Reason for use the ID for ordering is that the waitlist logic uses the id for ordering waitlist queue. Other solution would be to change it to be using created_time.
Refs LINK-2187

LINK-2187 | fix(registration): order signups by id

---

linkedevents/settings.py

There were some issues pointing out the schema in different envs with different url and static configuration. 
This ditches the hardcoded static and uses django's static root for pointing the swagger-ui's schema file.
Refs LINK-2198

fix: use django's static root in swagger schema url config

---

events/api.py
events/filters.py
events/tests/test_event_filters.py
events/tests/test_event_get.py

There were `ProgrammingError` thrown when using `max `or `min_duration` filter with `hide_recurring_children` filter. This was because the `min_*` and `max_duration` filters were defined to use custom sql `WHERE` clauses without referring to which table the fields in the `WHERE` clause was referring to and there were other tables joined to the query by `hide_recurring_children` filter.
Solution was to convert these max and min_duration filters to be using django qs functions.
Also refactors the `max_` and `min_duration` filters away from `api.py` to filters.
Refs LINK-2203

LINK-2203 | fix(events): use django qs functions in max_* and min_duration filters

---

docker/django/Dockerfile

Use BUILDER_REGISTRY parameter to get configurable image registry.
Refs LINK-2204

build: use BUILDER_REGISTRY param in Dockerfile

---

linkedevents/settings.py

The removed code is unreachable due to SECRET_KEY being always defined in settings.py

refactor: remove obsolete .django_secret

---

registrations/signals.py
registrations/tests/test_registration_post.py

The original behaviour is seen as problematic when using old events as templates with new ones as an existing (old) info_url will prevent automatic updating when creating a new registration for the event.
refs: [LINK-2219](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2219)
[LINK-2219]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: always update offer info_url when creating new registration

---

registrations/api.py
registrations/tests/test_registration_get.py
registrations/tests/test_signup_get.py

Also revert a previous commit. Misunderstood the task.

feat(registrations): add ordering for registrations view 

---

registrations/models.py

This was causing random failures with two tests (`test_recurring_sub_event_put_cancellation_emails_sent_payments_not_refunded_for_super_event` and `test_recurring_sub_event_put_cancellation_emails_sent_signups_not_cancelled_for_super_event`) which assume that the notifications were sent in a certain order (desc pk). However, if an order is not specified, Postgres cannot guarantee an order, and that's exactly what happened here.
There were two ways of resolving this; either guarantee an order or change the test to be order-agnostic. In this case, I chose the path of least resistance.
I've no clue how to default order works, but it's probably related to the underlying data structures. It would also explain why the tests were failing randomly since there is some random data involved in the …

LINK-2210: fix randomly failing tests

---

registrations/tests/test_price_group_get.py

`test_price_group_list_ordering` failed in certain circumstances, e.g. `pytest -k order`. This PR fixes that issue.
PriceGroupViewSet orders the price groups by `description`, `description` is a translated field, and `PriceGroupFactory` overrides all languages with `"<lang> Price Group <seq>"`, where `<lang>` is the language code and the `<seq>` is a growing sequence of numbers. In certain circumstances, this causes the order to become something unexpected, e.g. with the descriptions `EN Price Group 9` and `EN Price Group 10`, the latter price groups would be placed first (because `"10"` > `"9"`).
Solved the issue by setting the translation directly and making sure that the correct translation is used.
Also refactored the test a bit. I'm not sure if I agree with the test using paging …

test(registrations): fix flaky test

---

linkedevents/settings.py

socket.gethostbyname() does not necessarily return a resolvable host name.

fix: gaierror when attempting to resolve unresolvable hostname in DEBUG

---

linkedevents/settings.py

ESPOO_API_EVENT_START_DAYS_BACK in conf was configured to be str. That caused errors and should be read as int.

fix(events): use espoo api days back conf as int

---

audit_log/middleware.py
audit_log/tests/test_middleware.py

In production requests path begins with /linkedevents/
Refs: LINK-2331

LINK-2331|fix: audit log production urls

---

events/importer/utils.py
events/search_index/utils.py
events/tests/test_search_index.py

When cleaning text to EventSearchIndex there were some issues with text with html tags that it did not separate words for tags like "`this<br/>would<br/>a<br/>single<br/>word`".
This adds spacing between to html tags so that the words can be extracted
Refs: LNK-2315

feat(events): add space separator to html tags

---

events/api.py
events/exporter/city_sdk.py
events/filters.py
events/importer/base.py
events/importer/enkora.py
events/importer/kulke.py
events/importer/lippupiste.py
events/importer/mikkelinyt.py
events/management/commands/populate_local_event_cache.py
events/models.py
events/templates/swagger/event_list_description.html
events/tests/importers/test_enkora.py
events/tests/importers/test_espoo.py
events/tests/test_event_filters.py
events/tests/test_event_get.py
events/tests/test_event_post.py
events/tests/test_event_put.py
events/tests/test_events_search.py
events/tests/test_filter_by_registration_capacities.py
events/tests/test_utils.py
events/tests/utils.py
events/utils.py
helevents/templates/rest_framework/event_list.html
notifications/tests/test_notifications.py
registrations/tests/test_utils.py
requirements.in
requirements.txt

Adds `sub_events` filter to events which to be pair with `hide_recurring_children` to include other selected filtering to the sub events of supers.
+ refactors pytz out 
+ some miney tests refactor
Refs: LINK-2260

LINK-2260 | Add sub_events filter to pair with hide_recurring_children 

---

linkedevents/settings.py

Use latest CORS variable naming convention from: https://pypi.org/project/django-cors-headers/
Refs: LINK-2188

LINK-2188: Update CORS variable naming

---

events/importer/enkora.py

There is a new Enkora course that needs this place. Tested by running the Enkora importer locally.
Refs: [LINK-2362](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2362)
[LINK-2362]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add Enkora place data for Kivikko ice hall

---

events/filters.py
events/search_index/postgres.py
events/search_index/utils.py
events/tests/test_event_filters.py
events/tests/test_search_index.py

Fulltext-search works more accurately,
when plain lists are used instead of sets.
Updated ordering to use "id" as secondary order.
This will guarantee same default order always.
Added and updated tests.
Refs: LINK-2373

LINK-2373: Use plain lists in fulltext search vectors

---

events/search_index/utils.py
events/tests/test_search_index.py

The return order of analyze results is not stable across systems. Possibly a linux vs OSX thing. This fix ensures that the results are returned sorted according to word bases.
refs: LINK-2373

fix: unstable result order from voikko analyze

---

events/api.py
events/filters.py
events/templates/swagger/event_list_description.html
events/tests/test_event_filters.py
helevents/templates/rest_framework/event_list.html

Allow full text searches to be sorted with `sort`-parameter explicitly.
Default to `-rank,id` sorting.
Update tests and documentation.
Refs: LINK-2378

LINK-2378: Update full text sorting

---

events/utils.py

Removed in Python 3.10
refs: LINK-2389

fix: import Mapping from collections.abc instead of collections

---

linkedevents/settings.py

Changed Sentry traces sample rate env value to be read only once to get rid of annoying excessive debug logs, and tweaked types in the traces sampler function to be more perfect.
Refs: [LINK-2367](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2367)
[LINK-2367]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Minor tweaks to Sentry traces sampler
