events/admin.py
events/migrations/0007_organization_admin_users.py
events/models.py

Closes https://github.com/City-of-Helsinki/linkedevents/issues/51 .

Add "admin_users" field to events.Organization.

---

events/api.py
events/tests/test_event_put.py

Closes https://github.com/City-of-Helsinki/linkedevents/issues/58 .

Add support for updating events via PUT.

---

events/api.py
requirements.txt

I fixed requirements.txt to limit some module versions to work with current City-of-Helsinki code.
Also parse_duration() is fixed and renamed as mentioned in Slack post.

Fixes to make fresh LE clone run without errors

---

events/api.py
events/tests/conftest.py
events/tests/test_event_post.py

Fixed multiple minor issues in EventSerializer, TranlatedModelSerializer and JSONLDRelatedField, removed unnecessary customisations and centralised logic to JSONLDRelatedField.

Improve event post put

---

events/management/commands/install_templates.py
events/routers.py
events/templates/rest_framework/api.html.example
linkedevents/settings.py
templates/rest_framework/api.html

As discussed today at Satamatalo

Remove Helsinki specific texts

---

events/importer/kulke.py

Use kulke events' caption as short_description

---

templates/rest_framework/api.html.example

Show correct API version on the front page

---

events/api.py

Fix double url encoding

---

events/api.py
events/tests/conftest.py
events/tests/test_event_post.py
events/tests/test_event_put.py

Validate that an event's start time or end time isn't in the past

---

events/management/commands/event_export.py
events/management/commands/event_import.py

Replace deprecated optparse with argparse in management commands

---

events/admin.py
linkedevents/settings.py
requirements.in
requirements.txt

Add Leaflet map for Place in admin UI

---

events/api.py
events/tests/conftest.py
events/tests/test_event_post.py

If name field is translated require it in atleast one language

Fix name validation

---

events/api.py
events/tests/conftest.py
events/tests/test_event_put.py

Disallow editing past events

---

events/api.py
requirements.txt

Upgrade Django REST Framework to 3.5.3

---

scripts/import.sh

Timeouts for commands (tprek seems to get stuck sometimes), dry logging

importer: timeout stuck commands (with notification), dry logging

---

events/api.py

Add sub_organization and rename parent to parent_organization.

Add sub_organization to Organization REST API

---

events/importer/kulke.py
events/tests/importers/test_kulke.py

Format description into html for kulke importer

---

events/importer/tprek.py

Note: you might need to increase import.sh timeout length for the first run.

Upgrade to TPR REST v4 API version

---

README.md
docker-compose.yml
docker/django/Dockerfile
docker/elasticsearch/Dockerfile
docker/postgres/Dockerfile
docker/postgres/docker-entrypoint.sh
local_settings.py.template

Dockerize project's development setup

---

events/api.py
events/tests/test_api.py
helevents/templates/rest_framework/event_list.html

Merge master into linked-courses

---

events/importer/base.py
events/importer/kulke.py
events/management/commands/event_import.py

Add Kulke course importer

---

events/importer/base.py

Event has now images as a ManyToMany field.

Fix image assignment while importing events/courses

---

events/api.py
events/tests/test_event_get.py

Fixes https://sentry.hel.ninja/aok/linkedevents-backend/issues/6725/

Avoid infinite recursion when both sub and super events expanded

---

events/importer/base.py
events/importer/espoo.py
events/importer/harrastushaku.py
events/importer/helmet.py
events/importer/kulke.py
events/importer/tprek.py
events/management/commands/event_import.py
events/models.py
linkedevents/settings.py

Added [Harrastushaku](http://nk.hel.fi/harrastushaku/) importer which imports courses and places. 
The PR includes also some changes outside the importer that were required to get the whole thing working. Details are in the commit messages.
Closes #276

Harrastushaku importer

---

.travis.yml
config_dev.toml.example
events/importer/base.py
linkedevents/settings.py
requirements.in
requirements.txt

Pulls all configuration from environment variables / KEY=VALUE style configuration file.
Wrt. issue #309

Environment-based configuration

---

.travis.yml

This also makes Travis run work again

Update Travis to use Postgres 10 and corresponding PostGIS

---

README.md
docker-compose.yml
docker/elasticsearch/Dockerfile

I recommend reviewing commit-by-commit :)

Remove elastic search from Docker

---

importers.md

I wanted to get the ball rolling with publishing the first importer documentation, to collect feedback if any arises.

Documenting importers

---

README.md
events/importer/harrastushaku.py
linked-courses-importers.md

Please review commit-by-commit if you think the changes are big :)

TH-40 HH importer location duplication fix

---

events/api.py
events/tests/test_api.py

Resolves https://github.com/City-of-Helsinki/linkedevents/issues/345

Add has_regular_users field to org serializer

---

events/importer/helmet.py

Resolves https://github.com/City-of-Helsinki/linkedevents/issues/351

Add a default offer to all events from Helmet

---

helevents/admin.py

Resolves https://github.com/City-of-Helsinki/linkedevents/issues/302

Display user's organizations in user admin

---

events/api.py
events/tests/conftest.py
events/tests/test_event_get.py

Resolves https://github.com/City-of-Helsinki/linkedevents/issues/280

Add event filtering by publisher ancestor

---

events/apps.py
events/signals.py
events/tests/conftest.py
events/tests/test_notifications.py
notifications/migrations/0003_create_default_user_created_template.py
notifications/models.py

Resolves https://github.com/City-of-Helsinki/linkedevents/issues/379

User created notification

---

events/api.py
events/tests/test_event_get.py
events/tests/test_keyword_get.py
events/tests/test_place_get.py
events/utils.py

Resolves https://github.com/City-of-Helsinki/linkedevents/issues/385

Show deleted parameter

---

events/importer/lippupiste.py

Resolves https://github.com/City-of-Helsinki/linkedevents/issues/384

Only update super-event if something changed

---

events/api.py
events/tests/test_event_get.py

Resolves https://github.com/City-of-Helsinki/linkedevents/issues/383

Keyword filters

---

events/tests/conftest.py
events/tests/test_event_get.py
events/utils.py
requirements-dev.in
requirements-dev.txt

Resolves https://github.com/City-of-Helsinki/linkedevents/issues/396

Tests for all use cases of `start` and `end` filters

---

events/api.py
events/tests/test_event_get.py

Resolves https://github.com/City-of-Helsinki/linkedevents/issues/402

Add `is_free` filter to event API

---

events/api.py
events/tests/test_event_get.py

Resolves https://github.com/City-of-Helsinki/linkedevents/issues/390

Return only undeleted sub events

---

events/importer/lippupiste.py

Resolves https://github.com/City-of-Helsinki/linkedevents/issues/393

Trim super-events in lippupiste importer

---

events/api.py
events/tests/test_keyword_get.py
helevents/templates/rest_framework/keyword_list.html

This PR adds trigram similarity based search for the keywords.

add keyword similarity search

---

events/importer/base.py

This PR fixes the creation of external links that are not bound to any particular offer and hence have no place in the Offers section.

fix external link creation

---

events/importer/harrastushaku.py
events/importer/util.py
requirements.in
requirements.txt

this PR adds reg link creation to hhaku importer

create registration link

---

events/importer/mikkelinyt.py
events/tests/test_importer_mikkelinyt.py

Added support for importing events from Mikkeli Nyt

Added an importer for Mikkeli Nyt  -events

---

events/models.py
events/tests/test_models.py
linkedevents/settings.py
linkedevents/urls.py
requirements-dev.in
requirements-dev.txt

-fix issue with image upload
-fix 'has_upcoming_events' to take into account also the ongoing events
-add debug toolbar

Small fixes and dev tools

---

events/api.py
events/tests/test_event_get.py
helevents/templates/rest_framework/event_list.html

Excludes all the events that have max age limit below or min age limit above the age specified. Suitable events with just one age boundary specified are returned, events with no age limits specified are excluded.

LINK-515 Select events suitable for certain age

---

docker-compose.yml
docker/django/Dockerfile
docker/django/docker-entrypoint.sh
linkedevents/settings.py

This PR makes some small changes to the docker-compose related development environment setup.

Development environment improvements

---

.dockerignore
.pre-commit-config.yaml
README.md
pyproject.toml
pytest.ini
requirements-dev.in
requirements-dev.txt
setup.cfg

This PR adds code quality related tools: black, flake8 and isort. Configuration for each of these tools is added as well. Result of running these tools for the whole code base shall follow in a separate PR.

LINK-1123 | Add code quality tools

---

events/importer/yso.py

Remove deprecated/unused bulk_mode and enforce importing only supported languages to avoid importing Northern Sami (language code "se") which was introduced to YSO sometime around 2022.

Fix YSO importer

---

.github/workflows/ci.yml
requirements-dev.in
requirements-dev.txt

The workflow setups the project and runs checks for migrations, black, flake8, isort, coverage and runs the tests.

Add Github Actions CI/CD workflow

---

registrations/api.py
registrations/tests/test_registration_admin_side.py

There wasn't any permission checks done for DELETE since `DestroyModelMixin` doesn't use the serializer at all. Currently permission check is done only in the serializer.
Also refactor the `test_basic_registration_functionality` into multiple unit test, which only test one thing.
Refs LINK-1122

LINK-1122 | Fix RegistrationViewSet checks permission on delete

---

docker/django/Dockerfile

Needed for production build.
Refs LINK-1158, LINK-1138, LINK-1081

Add dummy SECRET_KEY for collectstatic to Dockerfile

---

.prod/uwsgi_configuration.ini

Make uWSGI serve media files

---

events/api.py
events/importer/kulke.py
events/importer/osoite.py
events/importer/tprek.py
events/management/commands/add_helfi_topics.py
events/management/commands/add_helsinki_audience.py
events/management/commands/add_helsinki_topics.py

Improvements separated from #584

LINK-1274 | Code improvements

---

events/api.py

Fix error message of invalid **audience_min_age_gt** parameter
[LINK-1318](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1318)
[LINK-1318]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1318 | Fix error message to use correct parameter

---

helevents/templates/rest_framework/event_list.html
helevents/templates/rest_framework/image_list.html
helevents/templates/rest_framework/keyword_list.html
helevents/templates/rest_framework/keyword_set_list.html
helevents/templates/rest_framework/organization_list.html
helevents/templates/rest_framework/place_list.html
helevents/templates/rest_framework/root.html
helevents/templates/rest_framework/search_list.html

Update documentation to much current API
[LINK-1314](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1314)
[LINK-1314]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1314 |. Update API documentation

---

requirements-dev.txt
requirements.txt

Bump Django, sqlparse and requests

---

events/api.py
events/importer/kulke.py
events/keywords.py

This PR contains local changes which are present in a diff from the current production environment (and some minor refactoring). These changes need to be checked if they are still relevant.

LINK-1274 | Local changes from current production environment

---

events/api.py
events/tests/test_caching.py
linkedevents/test_settings.py
linkedevents/tests/conftest.py

Add check to not result in an error if cache is missing.
Refactor away duplicate code.
Refs LINK-1319

Missing cache error

---

events/management/commands/export_organizations.py

Add management command to export organization tree data to a csv -file.
Refs LINK-1290

Organization export

---

events/importer/base.py
events/importer/kulke.py

Currently the kulke importer does not use transactions, meaning that if it's interrupted, the result might contain inconsistencies.
Also a couple of other changes:
- handle super event metadata during super event creation instead of doing it separately afterwards
- default to using the first event's name for the super event's name in cases where no common part among the member event names is found
- use bulk create/update instead of looped creates/updates where possible
- delete existing super events if they only contain one event
N.B. the transaction change to `save_event` and `save_place` will affect all importers, not just kulke.

Use transactions in kulke importer

---

docker/django/Dockerfile
helevents/service_tasks/daily_tasks.sh
helevents/service_tasks/hourly_tasks.sh
requirements.in
requirements.txt

Refs [LINK-1080](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1080)
[LINK-1080]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Importer fixes

---

events/api.py
events/models.py
events/permissions.py
events/tests/test_event_images_v1.py
events/tests/test_models.py

Adjust permissions which users can edit images.
Refs LINK-1146

Link 1146/external user can upload and edit images

---

events/permissions.py
events/utils.py

Use of @cache caused each request to be permanently cached leading to rapid memory usage increase.
Ref LINK-1395

Fix memory leak with cache

---

events/api.py

Optimize related searches for event include (location and keywords).
Ref LINK-1396

Optimize related for event?include

---

events/management/commands/add_helsinki_audience.py

Ref https://helsinkisolutionoffice.atlassian.net/browse/LINK-1377

Add yso:p16596 tourists keywod to helsinki:audiences

---

.github/workflows/ci.yml
azure-pipelines-build.yml
azure-pipelines-dev.yml
azure-pipelines-stage.yml
azure-pipelines-test.yml

Update the various pipelines to use main as the primary branch. Simplify and remove staging build tags
Ref LINK-1438

Rename primary branch from develop to main

---

events/management/commands/add_helsinki_audience.py

Add yso:p7708 unemployed keyword to helsinki:audiences

---

requirements.in
requirements.txt

django-munigeo version bump to 0.3.9

---

linkedevents/settings.py

Fix static files not being accessible in production.

LINK-1487 | Fix static files in production

---

events/importer/yso.py

Add missing YSO replacement.
[yso:p21315](https://finto.fi/yso/fi/page/p21315) to [yso:p508301](https://finto.fi/yso-paikat/fi/page/p508301)
Refs [LINK-1524](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1524)
[LINK-1524]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1524: Add missing YSO replacement

---

requirements-prod.txt

Previous version had some security issues
Refs RAT-18

Bump uwsgi

---

events/importer/harrastushaku.py
events/tests/factories.py
events/tests/importers/test_harrastushaku.py

TPREK identifier will be used, if available, to find the correct `Place` for a location from harrastushaku.

LINK-1491 | Harrastushaku importer: Match addresses with TPREK id

---

linkedevents/test_settings.py

At the moment some tests are failing with following or similar error:
```
Traceback (most recent call last):
File "/Users/jorilindell/Projects/linkedevents/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/Users/jorilindell/Projects/linkedevents/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/jorilindell/Projects/linkedevents/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
return view_func(*args, **kwargs)
File "/Users/jorilindell/Projects/linkedevents/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
return …
```

Add FIELD_ENCRYPTION_KEYS to test_settings.py

---

registrations/permissions.py
registrations/tests/test_signup_group_patch.py
registrations/tests/test_signup_group_put.py
registrations/tests/test_signup_patch.py
registrations/tests/test_signup_put.py

This PR fixes the edge case that user belongs to registration user accesses and user is updating a signup or signup group created by user. Registration user access can update only presence_status field and signup creator can edit all other fields. So in this edge case user should be able to update all signup or signup group fields.
Also added strong identification for the tests that tested registration user access permissions to avoid false positives.
[LINK-1626](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1626)
[LINK-1626]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1626 | Allow registration user access to update signup created by the user

---

registrations/management/commands/encrypt_fields_with_new_key.py
registrations/tests/test_commands.py

Adds a management command that allows to encrypt existing encrypted data with a new encryption key.
[LINK-1590](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1590)
[LINK-1590]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1590 | Management command for encrypting fields with a new key

---

docker/django/docker-entrypoint.sh
requirements-prod.in
requirements-prod.txt

This PR adds `uwsgitop` for improved `uwsgi` monitoring for the production environment.

LINK-1558 | Add uwsgitop and stats server socket for monitoring

---

registrations/serializers.py
registrations/tests/test_signup_group_post.py

Blocks creating a signup group if at least one responsible signup has not been given in the group's `signups` list.
[LINK-1540](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1540)
[LINK-1540]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1540 | Don't allow to create a group without at least one responsible signup

---

helevents/templates/rest_framework/place_list.html

Fix show_deleted filter example for a Place

---

events/api.py
events/tests/test_event_get.py
events/tests/test_keywordset_post.py
events/tests/test_permissions.py
helevents/models.py
helevents/templates/rest_framework/event_list.html
helevents/templates/rest_framework/registration_list.html
registrations/api.py
registrations/tests/test_registration_get.py

- registration_admin_user parameter for events to get events whose registration the user can modify
- admin_user parameter for registrations returns also registrations where user is registration admin user
[LINK-1603](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1603)
[LINK-1603]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1603 | Search parameter to get registrations that current user can update

---

azure-pipelines-stage.yml
azure-pipelines-test.yml

[LINK-1710](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1710)
[LINK-1710]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build: test and stage deploy pipelines are triggered from build pipeline LINK-1710

---

events/api.py
events/tests/test_api.py
helevents/templates/rest_framework/organization_list.html

Adds boolean filter for including or excluding (true/false) dissolved organizations from the result.
Refs LINK-1716

LINK-1716 | Add dissolved filter to Organization api

---

events/api.py
events/tests/test_event_get.py

Original implementation fetched sub events without any select/prefetch related, causing thousands of redundant SQL queries.
Second commit cleans up serializer context logic for EventViewSet.
Ref: LINK-1725

Fix major performance issues with include=sub_events

---

events/api.py

Performance on staging was still bad in our test scenario, as the previous optimization reduced the query count by only 1500, leaving another 1400 redundant queries. 
For all events the following were missing:
* helevents_user (missing creators and modifier users of Event and Image)
* munigeo_administrativedivision_translation
Additionally for include=sub_events, the subevent prefetch queries were missing prefetches at least for 
* munigeo_administrativedivisiontype
* munigeo_muncipality
* events_place_divisions
* django_orghierachy_organization

perf: improve event listing prefetches (ROUND 2)

---

events/importer/enkora.py
events/tests/importers/test_enkora.py

After carefully evaluating import result with Liiikunta/Enkora people, improved accuracy of import. Lots of it.
All courses are imported as super events with course instances as sub-events.

Enkora importer V2

---

requirements.txt

Bump newly released django-orghierarchy.

chore: bump django-orghierarchy

---

helevents/service_tasks/hourly_tasks.sh

chore: enable hourly espoo importer

---

events/models.py
events/tests/factories.py
helevents/migrations/0008_serializablepublisher.py
helevents/models.py
helevents/tests/test_gdpr_api_get.py

Adds to gdpr-api/ GET data:
- Organizations where user is admin or regular user
- Events created by user 
Refs LINK-1698

LINK-1698 | Additions to gdpr api user data fetch

---

registrations/serializers.py
registrations/tests/test_registration_post.py
registrations/tests/test_registration_put.py

Fixes an internal error occurring if an existing registration user access is given in a new registration's payload. While the actual issue appears to be a caching issue (possibly cached registration user access is used when sending a new registration's payload), this PR effectively gets rid of the error by implementing the following changes:
- Using a different serializer for `RegistrationUserAccess` without the `id` field when creating a new registration.
- Accessing the optional `pk` field in `parser_context["kwargs"]` with the `get` method and returning an empty `RegistrationUserAccess` queryset if no registration PK is found.
[LINK-1844](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1844)
[LINK-1844]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1844?atlOrigin=ey …

fix: 500 error due to existing user access used in registration POST

---

pipelines/linkedevents-api-dev.yml
pipelines/linkedevents-api-release.yml
pipelines/linkedevents-api-review.yml

[OH-35](https://helsinkisolutionoffice.atlassian.net/browse/OH-35)
[OH-35]: https://helsinkisolutionoffice.atlassian.net/browse/OH-35?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build: pipeline upgrade

---

registrations/exports.py

Adds signup's date of birth information to the registration signups XLSX export.
[LINK-1895](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1895)
[LINK-1895]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1895 | Add Date of Birth Column to Signups XLSX Export

---

events/importer/espoo.py
events/tests/importers/test_espoo.py

Since events can be soft deleted, it is possible to get broken super event relations through the API event listing. This fix iterates recursively through the event data and drops events that have broken super event references.
Ref LINK-1925

fix: make espoo importer ignore orphaned events

---

events/importer/enkora.py
events/tests/importers/test_enkora.py

Improvements and changes agreed during Dec -23 and Feb -24

feat: further Enkora importer improvements as agreed with KUVA/Liikunta

---

.pre-commit-config.yaml
events/api.py
events/importer/enkora.py
events/importer/lippupiste.py
events/models.py
events/tests/test_event_post.py
events/tests/test_event_put.py
events/tests/test_image_delete.py
events/tests/test_keyword_get.py
events/tests/test_keyword_post.py
events/tests/test_place_get.py
events/tests/test_place_post.py
helevents/tests/test_admin.py
helevents/tests/test_gdpr_api_get.py
linkedevents/serializers.py
linkedevents/settings.py
registrations/exports.py
registrations/forms.py
registrations/notifications.py
registrations/serializers.py
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_group_delete.py
registrations/tests/test_signup_group_post.py
registrations/tests/test_signup_post.py
registrations/tests/test_utils.py
requirements-dev.txt
requirements-prod.txt
requirements.in
requirements.txt
web_store/tests/test_web_store_api_base_client.py

Upgrade several dependencies to their latest versions.
`elasticsearch` has been defined to use versions below 8 so it was not upgraded. Since `urllib3` is a dependency for it, it was not upgraded either to a version that wouldn't work with the project's `elasticsearch` version.
Bumping `wheel` from `0.42.0` to `0.43.0` seems to cause Snyk to think the package is vulnerable and the scan fails, yet the reported vulnerability has to do with much older versions. The scan succeeds if the version is kept at `0.42.0`.
Some code and formatting changes were also needed due to upgrading `djangorestframework` and `black`.
[LINK-1903](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1903)
[LINK-1903]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1903?atlOrigin=eyJpIjoiNWRkNTljNzYxN …

LINK-1903 | Upgrade dependencies

---

locale/fi/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
registrations/notifications.py
registrations/tests/management/test_mark_payments_expired.py

Email notification texts for expired recurring event payments were missing. This PR adds them.
[LINK-2007](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2007)
[LINK-2007]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2007 | Add missing recurring event payment expiration texts

---

events/importer/yso.py

After the `rdflib` update to version `6.3.2`, the `Graph` class no longer has the method `preferredLabel`. The YSO importer is still using the method, causing an `AttributeError` to be raised. This PR fixes the issue by implementing a slightly modified copy of the `preferredLabel` method as a utility function.
[LINK-2018](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2018)
[LINK-2018]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2018 | Broken graph.preferredLabel call in YSO importer

---

events/permissions.py
events/tests/conftest.py
events/tests/test_datasource_get.py
events/tests/test_keyword_post.py
events/tests/test_keyword_put.py
events/tests/test_keywordset_post.py
events/tests/test_keywordset_put.py
events/tests/test_organization_api.py
events/tests/test_organizationclass_get.py
events/tests/test_place_post.py
events/tests/test_place_put.py
events/utils.py
linkedevents/serializers.py

Superusers are no longer required to be organization admins / members to perform actions like creating or updating an organization.
[LINK-2026](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2026)
[LINK-2026]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2026 | Don't require organization membership from superusers

---

events/models.py
events/translation_utils.py
helevents/tests/test_gdpr_api_get.py

feat(gdpr-api): add translations to gdpr data

---

events/models.py
registrations/models.py
registrations/notifications.py
registrations/tests/test_models.py
registrations/tests/test_utils.py
registrations/utils.py

Adds support for creating calendar events for recurring event's sub-events and appending those to the ICS calendar.
[LINK-1989](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1989)
[LINK-1989]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1989 | ICS support for recurring events

---

registrations/serializers.py
registrations/tests/test_signup_patch.py

Due to faulty validation for the signup price group selection, `presence_status` cannot be patched for a signup if the registration has price group selections. This PR fixes the validation.
LINK-2105

fix: allow to patch presence_status regardless of price groups

---

events/importer/espoo.py

Error spams sentry and we have long given up hope that these issues will be resolved upstream.

fix: change logger error to info

---

registrations/tests/test_utils.py
registrations/utils.py

- Use exception chaining in all web store / Talpa util functions in `registrations.utils`.
- Add proper unit tests to `registrations/tests/test_utils.py` for all web store / Talpa util functions in `registrations.utils` that didn't have them.
[LINK-2123](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2123)
[LINK-2123]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-2123 | Web store util function improvements

---

helevents/utils.py

The helsinki_gdpr implementation expects that the delete function may return an ErrorResponse object. Returning a Response object was actually equal to returning None, and it did not prevent the deletion from proceeding in Profile and Keycloak.
Refs: LINK-2116

fix: GDPR disable feature

---

events/api.py
events/permissions.py
events/serializers.py
events/tests/test_organization_api.py

Allow only superusers to add or remove organizations' users.
[LINK-1463](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1463)
[LINK-1463]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LINK-1463: Only superusers can add or remove organization users

---

docker-compose.yml

chore: remove version from docker-compose

---

helevents/tests/test_gdpr_api_delete.py
helevents/utils.py
linkedevents/settings.py

Adds check logic for deletion of on going payments and upcoming signups
Refs LINK-2138

LINK-2138 | GDPR removal improvements

---

.git-blame-ignore-revs
README.md

Refs [LINK-2201](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2201)
[LINK-2201]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ruff related chores

---

registrations/api.py
registrations/tests/test_signup_get.py

fix(registrations): order signups in descending order

---

registrations/exports.py
registrations/tests/test_exporter.py

Also display full name as <last_name> <first_name>
Refs LINK-2200

fix(registration): order signups by signup order in excel

---

registrations/models.py
registrations/serializers.py
registrations/tests/test_signup_delete.py
registrations/tests/test_signup_group_delete.py
registrations/tests/test_signup_group_post.py
registrations/tests/test_signup_post.py

This reverts commit 5bbe2bc85768b06dddf7098694f1bc84f3b4ff3a.
refs: LINK-2232

fix(registration): reapply allow customer groups with zero price

---

events/api.py
events/filters.py
events/templates/swagger/event_list_description.html
events/tests/test_event_filters.py
helevents/templates/rest_framework/event_list.html

LINK-2262 | Add filter param to hide super events

---

.pre-commit-config.yaml
.prod/uwsgi_configuration.ini
docker/django/docker-entrypoint.sh
events/importer/enkora.py
events/management/commands/export_organizations.py
events/renderers/docx.py
events/tests/importers/test_enkora.py
events/tests/test_utils.py
registrations/tests/test_price_group_get.py
registrations/tests/test_registration_get.py
requirements-dev.in
requirements-dev.txt
requirements-prod.txt

This PR does some fine-tuning for uWSGI settings. Biggest change should be the one where a request is killed earlier if there's any queue. If each worker has at least one job in the queue, a request will only get 20 seconds to complete.

LINK-2290 | uWSGI performance improvements

---

events/search_index/utils.py
events/tests/test_search_index.py
linkedevents/settings.py

Updates:
- Add support for Voikko stopword classes (LINK-2271)
- Improve index special character handling (LINK-2315)

LINK-2271: Voikko stop words support

---

events/management/commands/rebuild_event_search_index.py

Delete the EventSearchIndex in batches to make it a bit faster.
Refs: LINK-2305

LINK-2305 | Delete EventSearchIndex in batches

---

events/tests/test_event_filters.py

Test all 6 different languages explicitly with language-specific indexes.
Refs: LINK-2302

LINK-2302: Parametrize fulltext language tests
